### ISSUE TITLE
提示未找到下单账号是怎么回事？

### ISSUE THREAD

**Issue by SparkJiao** [pjialin/py12306#10]
提示“未找到下单账号，3秒后再次查询”
我手动去12306看了一下，那张票在排队，然后预定不了

**Comment by SparkJiao** [comment]
我查到的那张票是是排队人数超过余票所以12306上也不能预定，就比较尴尬

**Comment by SparkJiao** [comment]
问题已解决：
配置文件中`QUERY_JOBS`中的`account_key`需要与`USER_ACCOUNTS`中的某一个账号的key相同

**Comment by adaaaaaa** [comment]
这个英国有注释提示一下更好。。。 @pjialin
