### ISSUE TITLE
log in id please!

### ISSUE THREAD

**Issue by ccs1605** [pjialin/py12306#100]
![screenshot from 2019-01-21 19-00-35](https://user-images.githubusercontent.com/23208578/51509709-06ad1700-1daf-11e9-904b-4b44d845c36e.png)
 log in as adim thank you.

**Comment by lwb9428000** [comment]
What happened?The account is admin, and the password is password

**Comment by ccs1605** [comment]
thank you for your response!

**Comment by lwb9428000** [comment]
> thank you for your response!

You can change the login name and password in the env.py file
