### ISSUE TITLE
验证码反复识别问题

### ISSUE THREAD

**Issue by Gahon1995** [pjialin/py12306#101]
突然发现若快豆子使用完了，查看了一下识别记录，发现每隔几分钟就会有一个识别记录，日志里边隔一会儿会出现一个查询余票失败，状态码500，开了cdn，不知道和这个有没有关系

![wx20190122-140627](https://user-images.githubusercontent.com/26372413/51515752-e1241a00-1e4f-11e9-8bcd-48c6b83028a6.png)

**Comment by pjialin** [comment]
这个是一直重新登录造成的，跟网络环境有关系，如果网络被限制了就会频繁掉线重新登录，建议更换网络环境或者使用免费打码

**Comment by lwb9428000** [comment]
> 这个是一直重新登录造成的，跟网络环境有关系，如果网络被限制了就会频繁掉线重新登录，建议更换网络环境或者使用免费打码

我放在青云上也是，充了 50 块钱都不够用。尴尬
