### ISSUE TITLE
抢到票以后不会自动停止，同时会出现多次下单的情况

### ISSUE THREAD

**Issue by Gahon1995** [pjialin/py12306#104]
任务内容是抢硬卧和硬座，刚好同时放票了，于是出现了硬卧和硬座都下单的情况，同时下单成功以后并不会停止查询任务，反而会继续查询`

![cg](https://user-images.githubusercontent.com/26372413/51530954-13953d80-1e77-11e9-92fc-68fb4e73de9c.png)

**Comment by pjialin** [comment]
重复下单这个我后面优化下，看日志任务已经结束了，是否是添加了多个重复任务？
