### ISSUE TITLE
提交订单成功，检查订单失败！！！

### ISSUE THREAD

**Issue by Starbucksstar** [pjialin/py12306#107]
[ 查询到座位可用 出发时间 20190211 车次 G858 座位类型 二等座 余票数量 1 ]
检查完成 开始提交订单 
提交订单成功
检查订单失败，错误原因 None（第二种：提交订单失败，错误原因 -）

**求解，这种情况是因为余票不足吗**

**Comment by pjialin** [comment]
更新下最新代码
