### ISSUE TITLE
测试没问题，但是开始python main.py失败

### ISSUE THREAD

**Issue by civalias** [pjialin/py12306#111]
web上一切正常，有时会提示查询余票请求失败，状态码 500
![_20190123115807](https://user-images.githubusercontent.com/46922078/51582786-aaf6a100-1f08-11e9-8108-4be23c601c5c.png)
![_20190123121211](https://user-images.githubusercontent.com/46922078/51582787-aaf6a100-1f08-11e9-854c-09494b0a428d.png)
请问这个要怎么解决呢？

**Comment by Gahon1995** [comment]
看起来没有啥错误，终端那个警告忽略即可，如果需要在终端输出的话，将输出到文件设置关闭即可

**Comment by Hamishcn** [comment]
“余票请求失败，状态码 500”此警告對軟體使用造成影響十分微小，正常情況，可忽略，人人都有。
