### ISSUE TITLE
提交订单失败，错误原因 网络错误

### ISSUE THREAD

**Issue by gyz147** [pjialin/py12306#117]
=== 正在进行第 22837 次查询 上海 -> 太原 === 2019-01-24 08:58:53.406248
出发日期 2019-02-01: 上海 - 太原                Z196-N          安全停留 0.78
[ 查询到座位可用 出发时间 20190201 车次 Z196 座位类型 硬卧 余票数量 1 ]
检查完成 开始提交订单
提交订单失败，错误原因 网络错误

**Comment by Hamishcn** [comment]
有@可能。

Sincerely,

Hamish

Tseung Kwan O

Hong Kong Special Administrative Region

________________________________
发件人: 弓永壮 <notifications@github.com>
发送时间: Thursday, January 24, 2019 2:26:16 PM
收件人: pjialin/py12306
抄送: Hamish; Comment
主题: Re: [pjialin/py12306] 提交订单失败，错误原因 网络错误 (#117)


更新过了这样是不是缓存问题

第 31464 次查询 上海 -> 太原 2019-01-24 14:25:19
[ 查询到座位可用 出发时间 20190201 车次 Z196 座位类型 硬座 余票数量 1 ]
检查完成 开始提交订单
提交订单成功
检查订单成功
排队失败，目前排队人数已经超过余票张数
出发日期 2019-02-01: 上海 - 太原 Z196 耗时 0.03 停留 0.73
出发日期 2019-02-01: 上海 - 阳泉北 Z196 耗时 0.03 停留 0.6
出发日期 2019-02-01: 上海 - 石家庄北 Z196 耗时 0.04

―

**Comment by pjialin** [comment]
duplicate in #109
