### ISSUE TITLE
登陆不上

### ISSUE THREAD

**Issue by gyz147** [pjialin/py12306#122]
[ 查询到座位可用 出发时间 20190202 车次 Z196 座位类型 软卧 余票数量 1 ]
检查完成 开始提交订单
查询任务 上海 -> 太原 正在验证乘客信息
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试

**Comment by lfglfg11** [comment]
IP被封了

**Comment by gyz147** [comment]
不是IP被封了  正常得时候能登陆   一有余票准备抢得时候就登录不上去了

**Comment by Hamishcn** [comment]
心跳检测缩短一下

**Comment by jiangqm** [comment]
我也是这样，不知道怎么解决。心跳间隔缩短还是不行

**Comment by jiangqm** [comment]
请问报这个错的原因是因为验证码打不上还是12306账号密码错误？还是因为网络延迟高？

**Comment by pjialin** [comment]
免费打码的问题，最新提交已经修复了

**Comment by pjialin** [comment]
https://github.com/pjialin/py12306/commit/66ad9c9e5cfea9f62ef3d798b5cd69840320d9ac
