### ISSUE TITLE
请问下，后端的管理平台是什么UI模板的开发？

### ISSUE THREAD

**Issue by freedomofme** [pjialin/py12306#123]
我知道后端是flask，请问下具体的UI框架是哪一个？

**Comment by Hamishcn** [comment]
这是opensource....

**Comment by Gahon1995** [comment]
UI，感觉像vue，elementUI

**Comment by doublewinter0** [comment]
浏览器端 vue 插件亮了，所以应该是用 vue 写的，或者底层是基于 vue。

**Comment by pjialin** [comment]
是的， 基于 ElementUI [https://element.eleme.io/#/zh-CN](https://element.eleme.io/#/zh-CN)
