### ISSUE TITLE
使用nginx进行反向代理时出错

### ISSUE THREAD

**Issue by golezi** [pjialin/py12306#124]
nginx部分配置
location /12306/{
    proxy_pass http://127.0.0.1:8008/;
}

当我访问 https://domain.com/12306/ 
js css img等资源的请求地址是
https://domain.com/static/js/vendor.aebd1de04bf90e88d9c7.js
该地址返回404

实际上应该访问
https://domain.com/12306/static/js/vendor.aebd1de04bf90e88d9c7.js

**Comment by pjialin** [comment]
你这样配置到二级目录需要 rewrite 一下资源的路径

未测试，仅供参考
```nginx
rewrite  ^/static/(.*)$  /12306/static/$1  break;
```
