### ISSUE TITLE
可变对象作为默认参数的建议

### ISSUE THREAD

**Issue by Makecodeeasy** [pjialin/py12306#127]
读了下源码， helpers.request.Request 这个类中使用了可变对象(空字典)作为json方法的默认参数，这可能会引发bug

` def json(self, default=None):
        """
        重写 json 方法，拦截错误
        :return:
        """
        if default is None:
            default = dict()
        from py12306.app import Dict
        try:
            result = self.old_json()
            return Dict(result)
        except:
            return Dict(default)`
建议修改成这样。

**Comment by pjialin** [comment]
空字典最后也会转成 Dict 对象，暂没看出有什么问题，先关了。如果有具体 bug，欢迎重新打开 issue

**Comment by Makecodeeasy** [comment]
嗯，因为如果出现异常，一般也不会取操作空字典，所以不会有问题，但是最好不要用可变对象作为默认参数， 这跟后面的Dict转换没关系吧， 如果你代码里操作了空字典，后面即使用Dict转换了，还是会有问题的
