### ISSUE TITLE
源码学习之问题

### ISSUE THREAD

**Issue by arckalsun** [pjialin/py12306#129]
在文件https://github.com/pjialin/py12306/blob/master/py12306/cluster/cluster.py中
有两行代码，看不懂中间的冒号什么意思，求大佬解释！
 
44.  `session: Redis = None`
45.  `pubsub: PubSub = None`

**Comment by yyscamper** [comment]
这是Python的语法：type hints, 用于标注变量的类型，方便阅读代码，一些IDE也会借助于这个功能做语法提示。

具体的可以参考：
https://www.python.org/dev/peps/pep-0484/
