### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by SCUTJcfeng** [pjialin/py12306#130]
> Compound statements (multiple statements on the same line) are generally discouraged.

建议作者参考PEP8规范[https://www.python.org/dev/peps/pep-0008/#other-recommendations](url)

**Comment by pjialin** [comment]
个人觉得写在一行会比较美观，再起一行反而比较臃肿。当然，每个人想法当然不一样，也没有绝对正确，暂不考虑修改
