### ISSUE TITLE
[邮箱通知,发送邮箱为qq，邮箱授权也打开了，授权码也填入  还是报错

### ISSUE THREAD

**Issue by zkl99999** [pjialin/py12306#135]
邮件发送失败，请手动检查配置，错误原因 [Errno 11004] getaddrinfo failed

`# 邮箱配置
EMAIL_ENABLED = 1  # 是否开启邮件通知
EMAIL_SENDER = '7@qq.com'  # 邮件发送者
EMAIL_RECEIVER = '@163.com'  # 邮件接受者 # 可以多个 [email1@gmail.com, email2@gmail.com]
EMAIL_SERVER_HOST = 'stmp.qq.com'  # 邮件服务 host
EMAIL_SERVER_USER = '7@qq.com'  # 邮件服务登录用户名
EMAIL_SERVER_PASSWORD = 'xxxxxxxx'  # 填写的授权码

**Comment by pjialin** [comment]
目前测试邮箱功能没有问题，可以仔细检查下配置，上面提供的信息不完整，也看不出来什么问题

**Comment by SiDneY-lxp** [comment]
EMAIL_SERVER_HOST 写错了 是smtp.qq.com
