### ISSUE TITLE
[Suggestion] 路线规划

### ISSUE THREAD

**Issue by yyrdl** [pjialin/py12306#139]
12306 票难买仅靠搞多进程，让机器人刷票是没有意义的，你刷我刷大家刷，0和游戏，12306真是凄惨，不仅要面对大量真实用户的请求，还得应付一堆爬虫 orz！

票难买是一个资源问题，节假日的时候存在热点，比如到北京，或者从北京出发，北京是热点城市，但天津、石家庄就没那么热，所以我觉得结合余票情况出一个路线规划的应用更能解决实际问题。

**Comment by golezi** [comment]
就是不想转车才一直刷想买直达的
