### ISSUE TITLE
验证码下载失败 错误原因: 返回数据为空 5 秒后重试

### ISSUE THREAD

**Issue by Geocld** [pjialin/py12306#140]
今天测试发现出现这样的错误，是什么原因呢？

**Comment by Geocld** [comment]
看了下是http://60.205.200.159/api这个免费打码的api失效了

**Comment by pjialin** [comment]
偶尔出现验证码下载失败是正常的，看了下免费打码确实失效了

**Comment by 12374598858** [comment]
https://12306.jiedanba.cn   验证码识别接口

**Comment by Geocld** [comment]
@12374598858 thks，这个接口可以用，建议 @pjialin 更新加接口

**Comment by pjialin** [comment]
@12374598858 @Geocld 感谢，已更新
