### ISSUE TITLE
12306接口是不是换了，一直登录失败

### ISSUE THREAD

**Issue by 60ke** [pjialin/py12306#144]
正在下载验证码...
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试
验证码验证成功 开始登录...
登录失败 错误原因: 网络错误
账号正在登录中，3 秒后自动重试
账号正在登录中，3 秒后自动重试

**Comment by tyamm** [comment]
我也是一样，日志如下~~~

正在下载验证码...
验证码验证成功 开始登录...
登录失败 错误原因: 网络错误

**Comment by zanemmm** [comment]
+1

**Comment by pjialin** [comment]
看了下是 12306 开启了浏览器特征码识别，简单处理了下，更新下应该可以了

**Comment by 60ke** [comment]
现在登录没问题的了但是下单的时候，出现了获取乘客列表失败的log

**Comment by tyamm** [comment]
我也同样，然后再重启下，连登录都有问题了。使用的是若快打码。 报错如下

5 秒后重新获取验证码
正在下载验证码...
打码失败: 错误原因 从免费打码获取结果失败
5 秒后重新获取验证码
正在下载验证码...
验证码验证成功 开始登录...
登录失败 错误原因: 网络错误

**Comment by tyamm** [comment]
我现在也一样，重启一下，连登录都有问题了。使用的是若快打码接口，报错如下：
正在登录用户 15078880116
正在下载验证码...
验证码验证失败 错误原因: None
5 秒后重新获取验证码
正在下载验证码...
验证码验证成功 开始登录...
登录失败 错误原因: 网络错误

而且还会出现多次登录才能登录成功，我今天就用了近30次识别·················

**Comment by 12374598858** [comment]
@tyamm 用免费打码接口啊。

**Comment by tyamm** [comment]
@12374598858 免费的用不了。我挂在了台湾服务器上~

**Comment by SunYanCN** [comment]
@tyamm 有可能是你用了代理，看看你谷歌浏览器是不是开了谷歌访问助手之类的，关掉就行了

**Comment by zeal-github** [comment]
依旧登录失败:网络错误
而且不知道为什么若快打码冲了5块钱几分钟就能搞没了。不过现在免费打码接口能用
但是登录不上去

**Comment by 12374598858** [comment]
@zeal-github 免费的一直能用啊。

**Comment by pjialin** [comment]
目前已经修改为程序生成浏览器标识，先关了
