### ISSUE TITLE
不能识别学生票和成人票

### ISSUE THREAD

**Issue by kettly1260** [pjialin/py12306#150]
由于现在是非学生票购票时间，但是买票的时候会调用学生身份买票，导致购票失败。能不能区分一下成人和学生呢？毕竟不改的话每次下单还要提前修改12306信息

**Comment by kbj** [comment]
用唯一序号形式指定乘车人就行。[https://github.com/pjialin/py12306/blob/master/env.py.example](url)里面有详细说明，按照说明填写
