### ISSUE TITLE
验证有问题

### ISSUE THREAD

**Issue by yelvlab** [pjialin/py12306#151]
>> 第 85182 次查询 dg -> yw 2019-04-02 11:56:45
验证码验证失败 错误原因: None
5 秒后重新获取验证码

经常报上面的错误，我开始任务的登录没问题，然后我直接去12306买票也没问题，12306bypass也没问题，这是什么情况，若快也有钱，还有我在用免费平台的时候也打不了。

**Comment by yelvlab** [comment]
补充一下，这个问题都是出现在任务中间重新登录的时候，然后后面还会跟着

验证码验证成功 开始登录...
登录失败 错误原因: 网络错误

可是我的网络一直可以用啊

**Comment by pjialin** [comment]
昨天修复了登录失败的问题，更新下试试

**Comment by yelvlab** [comment]
好，我中午更新试一下，感谢您的贡献

**Comment by AkkunYo** [comment]
> 昨天修复了登录失败的问题，更新下试试

我刚才更新的，依然是中间重新登录出现问题
重新结束开始任务就又可以认证成功了
![image](https://user-images.githubusercontent.com/22427163/55448922-2dcc6400-55fc-11e9-8f36-2b334c052d98.png)

**Comment by Disappointing** [comment]
> > 昨天修复了登录失败的问题，更新下试试
> 
> 我刚才更新的，依然是中间重新登录出现问题
> 重新结束开始任务就又可以认证成功了
> ![image](https://user-images.githubusercontent.com/22427163/55448922-2dcc6400-55fc-11e9-8f36-2b334c052d98.png)
我也是登录失败,更新的话是不是重新clone一次就行了

**Comment by pjialin** [comment]
@Disappointing 

更新，在项目目录下 `git pull` 就可以了

**Comment by pjialin** [comment]
已更新浏览器标识计算算法，登录失败的更新下代码再试试

**Comment by jasonqiao36** [comment]
我也遇到了，经常出现网络错误

**Comment by lisy27** [comment]
更新了代码还是报错
查询余票请求失败	状态码 302   	错误原因 Moved Temporarily   
验证码验证成功 开始登录...
登录失败 错误原因: 网络错误

**Comment by ivangreat** [comment]
我得也是网络错误啊 还报错 JPEG Corrupt data

**Comment by amiraja** [comment]
what is problem

**Comment by jianhun9527** [comment]
一直提示的网络失败，但网络是一直有用的，有人能提供一份成功过的配置文件吗？

**Comment by Alion548** [comment]
提示：
```
正在下载验证码...
打码失败: 错误原因 从免费打码获取结果失败
5 秒后重新获取验证码
```

**Comment by pjialin** [comment]
通过这个 issue #200 讨论吧，这个先关了
