### ISSUE TITLE
开启LOG输出至文件后报错

### ISSUE THREAD

**Issue by inkuxuan** [pjialin/py12306#16]
> [2019-01-14 17:25:12,974] ERROR in app: Exception on /log/output [GET]
> Traceback (most recent call last):
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
>     raise value
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_jwt_extended\view_decorators.py", line 103, in wrapper
>     return fn(*args, **kwargs)
>   File "C:\Users\inkux\Desktop\py12306\py12306\py12306\web\handler\log.py", line 39, in log_output
>     linecache.updatecache(file)
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\linecache.py", line 137, in updatecache
>     lines = fp.readlines()
>   File "C:\Users\inkux\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 3515: invalid start byte

持续上述报错，在配置文件使用
`OUT_PUT_LOG_TO_FILE_ENABLED = 0`
后解决，但因此无法使用Web查看Log

**Comment by pjialin** [comment]
已修复
