### ISSUE TITLE
免费打码失败（以及临时补丁..）

### ISSUE THREAD

**Issue by Lowmatinal** [pjialin/py12306#160]
今天早上发现一直提示打码失败
然后发现项目中还有一个打码接口

[这里](https://github.com/pjialin/py12306/blob/8d4ea3066abd1767b7ec5b3046743221156f55dc/py12306/helpers/OCR.py#L75)
加上
`if result.get('success'):`
`position = result.get('success')`
`return position.replace('(', '').replace(')', '').split(',')`

暂时能用，等作者更新啦

**Comment by pjialin** [comment]
那个是免费打码的，不过现在接口已经失效了。
