### ISSUE TITLE
获取RAIL_DEVICEID失效

### ISSUE THREAD

**Issue by Louis14lan** [pjialin/py12306#168]
## 文件位置
py12306/user/job.py

## 问题描述
在`https://kyfw.12306.cn/otn/HttpZF/logdevice`接口中，请求`body`里的`algID`是可以通过`self.request_alg_id()`获取，但是通过`_get_hash_code_params()`获取的`hashCode`与浏览器中的不符，因此登陆失败。登陆登录返回信息如下图：
![image](https://user-images.githubusercontent.com/15846506/59477233-dc0b4a00-8e86-11e9-80f1-2ba49046cc72.png)

**Comment by pjialin** [comment]
已更新
