### ISSUE TITLE
API_FREE_CODE_QCR_API 这个接口返回的格式是啥

### ISSUE THREAD

**Issue by mansonami** [pjialin/py12306#169]
这个接口返回的例子是啥？什么格式？       

 if result.get('success') and result.get('data.check'):
            check_data = {
                'check': result.get('data.check'),
                'img_buf': img,
                'logon': 1,
                'type': 'D'

result.get('data.check') 谁能给个样本例子

**Comment by pjialin** [comment]
已经失效了
