### ISSUE TITLE
这边运行监测，明明有票提交订单也是成功的，不过监测订单就失败了。

### ISSUE THREAD

**Issue by cwb2819259** [pjialin/py12306#173]
>> 第 53 次查询 鞍山西 -> 上海虹桥 2019-09-04 16:40:02
[ 查询到座位可用 出发时间 20190920 车次 G1226 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单
提交订单成功
检查订单失败，错误原因 余票不足！

这里是什么问题

**Comment by marvin9002** [comment]
订单检测参数不对

**Comment by longye45** [comment]
这个问题怎么解决呢，飞猪可以下单本软件不可以

**Comment by pjialin** [comment]
已经修复了
