### ISSUE TITLE
运行脚本出现网络错误

### ISSUE THREAD

**Issue by hongshengxin** [pjialin/py12306#177]

**Comment by LiuDanK** [comment]
同样出现这个问题

**Comment by JonsenMa** [comment]
“查询余票请求失败	错误原因 网络错误”

**Comment by 1874yin** [comment]
20190910运行脚本。
‘登陆失败 错误原因 网络错误“。
尝试过更换电脑，替换手动cookie均失败。

**Comment by Figlure** [comment]
同，验证成功，登录失败[图片]

**Comment by Figlure** [comment]
验证码验证成功 开始登录...
登录失败 错误原因: 网络错误

**Comment by Figlure** [comment]
> 验证码验证成功 开始登录...
> 登录失败 错误原因: 网络错误


修改cookie后已解决

**Comment by WhitCrow** [comment]
错误："查询余票请求失败        错误原因 网络错误"
版本：c09b442
环境：python3.7

**Comment by WhitCrow** [comment]
error：“验证码验证成功 开始登录...
登录失败 错误原因: 网络错误”
python版本：3.7
环境：Debian 4.9.30

**Comment by Jnjie1895** [comment]
我更新了cookie之后就成功了，想问下你们是怎么更新cookie的

**Comment by pjialin** [comment]
Cookie 获取已迁移到服务器，更新下代码即可
