### ISSUE TITLE
状态码500 ，查询请求失败，是ip被封了么

### ISSUE THREAD

**Issue by blindlq** [pjialin/py12306#18]

**Comment by blindlq** [comment]
![image](https://user-images.githubusercontent.com/26007393/51108195-4bbfcf00-182c-11e9-9951-6229baf43123.png)

**Comment by pjialin** [comment]
一般是 ip 被限制了，部分请求会失败

**Comment by blindlq** [comment]
一定要开启打码才能下单么。昨天运行了一下docker，后面就启动不了

**Comment by pjialin** [comment]
@blindlq  对，登录需要验证码的

**Comment by blindlq** [comment]
后面几次docker启动不了也是这个原因么，免费打码失败了，导致docker启动就挂了。

**Comment by pjialin** [comment]
不是，如果 docker 启动不了，贴下日志

**Comment by blindlq** [comment]
![image](https://user-images.githubusercontent.com/26007393/51154565-350e8c00-18af-11e9-8f6b-6616eff0f68b.png)
好像是我的锅，非法字符引起的
