### ISSUE TITLE
如何清除查询记录？

### ISSUE THREAD

**Issue by lhpmain** [pjialin/py12306#191]
如何清除查询记录？现在查询有几W的了，能否有个清除的选项？
还有，如果下单成功就自动停止查询的功能也加上就好了!

**Comment by luopojianshi** [comment]
试一下这个 echo '' > runtime/12306.log

**Comment by lhpmain** [comment]
>> 第 403 次查询 深圳北 -> 贺州 2019-09-17 13:46:58		

还是一样的

**Comment by pjialin** [comment]
删除下 `runtime/query/status.json` 就可以了
