### ISSUE TITLE
bark 推送消息到设备 有谁做过吗 

### ISSUE THREAD

**Issue by 572501797** [pjialin/py12306#194]
我这边推送没有效果

**Comment by pjialin** [comment]
我这测试了下是可以用的，可以检查下配置，如果没有效果，补充下操作步骤

**Comment by 572501797** [comment]
我下载了app 然后配置这一块 BARK_ENABLED = 0
BARK_PUSH_URL = 'https://api.day.app/eBH2V7LAqji8M7YkqfG5ZXXX/买到票了'  有什么不对吗
