### ISSUE TITLE
感谢分享，显示有票，但是提交订单失败

### ISSUE THREAD

**Issue by xiaoxie110** [pjialin/py12306#2]
提交订单失败
![image](https://user-images.githubusercontent.com/5236520/50963875-d640bf80-1508-11e9-8966-79a892c321c5.png)

**Comment by pjialin** [comment]
看着像是 ip 被限制了，一直出错吗

**Comment by o-water-o** [comment]
我也是相同的问题
显示有票但是提交订单失败
![default](https://user-images.githubusercontent.com/23520128/51072466-2ac87400-169c-11e9-997d-ec2061fb8169.PNG)

**Comment by pjialin** [comment]
这个情况，一般是 IP 被限制了， 12306 返回了空数据，我再优化下输出

**Comment by Ctum** [comment]
可以做成有余票就邮件通知吗

**Comment by rickyi22** [comment]
想问下 “未找到下单账号”， 是怎么解决呀， 那个account_key 我应该填什么呢

**Comment by pjialin** [comment]
@rickyi22 先关了，有问题可以另开 issue

**Comment by rickyi22** [comment]
嗯嗯~ 问题我已经在closed issue里解决了~  多谢大佬 已经买到票拉~

**Comment by pjialin** [comment]
哈哈，恭喜🎉
