### ISSUE TITLE
order_id返回test。。。

### ISSUE THREAD

**Issue by chenneyhuang** [pjialin/py12306#202]
上面说我车票购买成功。。但是订单后返回了个test。。。登录账号并没有发现有订单。。。

检查完成 开始提交订单
# 车票购买成功，订单号 test #
当前任务已结束
[ 查询到座位可用 出发时间 20191006 车次 D7178 座位类型 二等座 余票数量 1 ]
检查完成 开始提交订单
# 车票购买成功，订单号 test #
当前任务已结束

**Comment by pjialin** [comment]
应该是配置中打开了 Debug 吧 ?

**Comment by chenneyhuang** [comment]
是的。。。config.py 里的debug设为True了。。。谢谢。。。
