### ISSUE TITLE
嗯，现在服务器有点抗不住，做了限流，一般重试几次就可以了

### ISSUE THREAD

**Issue by lhpmain** [pjialin/py12306#205]
嗯，现在服务器有点抗不住，做了限流，一般重试几次就可以了

跑在本地的话可以通过 docker 镜像
```
docker run --rm -p 8000:8000 pjialin/12306-ocr:latest
```
然后修改 `py12306/helpers/api.py`
```
API_FREE_CODE_QCR_API  = 'http://0.0.0.0:8000/check/'
```

_Originally posted by @pjialin in https://github.com/pjialin/py12306/issues/200#issuecomment-533395368_

**Comment by lhpmain** [comment]
请问下，支持docker那些版本，我在Centos7的环境下安装18.03.1-ce  不能跑。

**Comment by lhpmain** [comment]
docker启动容器之后马上又自动关闭了的现像。

**Comment by pjialin** [comment]
上面提供的参数是以前台任务运行，在后台运行可以使用
```
docker run -d -p 8000:8000 pjialin/12306-ocr:latest
```
如果还是有问题，请提供下具体信息，怎么操作的，输出是什么

**Comment by sagehou** [comment]
有没有办法做个arm的docker
