### ISSUE TITLE
ERROR: Package 'pyppeteer' requires a different Python: 2.7.5 not in '>=3.5'

### ISSUE THREAD

**Issue by EasonQwQ** [pjialin/py12306#212]
你好，我是centos7的系统，自带的py2，但是我已经安装了py3，也改了默认的py为py3（或许？因为我在命令行输入 python -V 结果是3.7.）
```
[root@iZuf6aa80jpvwyyd7z4e4cZ py12306]# python
Python 3.7.1 (default, Sep 26 2019, 21:13:15) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux

```
但是执行
` pip install -r requirements.txt`这一步的时候总是跳出来
`ERROR: Package 'pyppeteer' requires a different Python: 2.7.5 not in '>=3.5'`
已经在搜索引擎搜索过问题，但是没有找到解决办法，请问该如何解决？

**Comment by EVINK** [comment]
你的pip是不Python2 的呀 

![image](https://user-images.githubusercontent.com/14816851/65746898-996a3680-e132-11e9-93a5-2e5e40c1e438.png)

wget http://cdn.evink.cn/developer/get-pip.py
python(3) get-pip.py

**Comment by pjialin** [comment]
`pip --version` 确认下关联的是否是 python3

**Comment by simonqian** [comment]
![image](https://user-images.githubusercontent.com/6582909/71310361-44e30880-244e-11ea-8777-4ebfe28fca3c.png)
我这是为啥啊，pip关联的都是python2.7
我也遇到跟题主一样的问题
`pyppeteer requires Python '>=3.5' but the running Python is 2.7.14`
