### ISSUE TITLE
未找到下单账号，3 秒后继续查询

### ISSUE THREAD

**Issue by KeymanLai** [pjialin/py12306#216]
LOG如下显示.此为什么原因引起的?

>> 第 181 次查询 深圳 -> 广州 2019-09-30 15:40:53
[ 查询到座位可用 出发时间 20191004 车次 C7012 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
未找到下单账号，3 秒后继续查询
[ 查询到座位可用 出发时间 20191004 车次 C7136 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
未找到下单账号，3 秒后继续查询
[ 查询到座位可用 出发时间 20191004 车次 C7092 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
未找到下单账号，3 秒后继续查询

出发日期 2019-10-04: 深圳 - 广州
C7012
C7136
C7092
G72
G1002
*耗时 0.89
停留 0.89
>> 第 182 次查询 深圳 -> 广州 2019-09-30 15:41:06
[ 查询到座位可用 出发时间 20191004 车次 C7012 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
用户 赖思恒 心跳正常，下次检测 120 秒后
未找到下单账号，3 秒后继续查询
[ 查询到座位可用 出发时间 20191004 车次 C7136 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
未找到下单账号，3 秒后继续查询
[ 查询到座位可用 出发时间 20191004 车次 C7092 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
未找到下单账号，3 秒后继续查询

出发日期 2019-10-04: 深圳 - 广州
C7012
C7136
C7092
G72
G1002
*耗时 0.29
停留 0.99
>> 第 183 次查询 深圳 -> 广州 2019-09-30 15:41:16

**Comment by bnpzsx** [comment]
env.py中'account_key'和下面的'key'对应
![QQ截图20191001092114](https://user-images.githubusercontent.com/22561030/65927606-ebf66c00-e42c-11e9-907e-9b2fceb3827b.jpg)
![QQ截图20191001092150](https://user-images.githubusercontent.com/22561030/65927609-ed279900-e42c-11e9-85fe-8516e9603e04.jpg)
