### ISSUE TITLE
打码失败了

### ISSUE THREAD

**Issue by LeiyuanBlog** [pjialin/py12306#223]
ocr_1      | 172.21.0.3 - - [17/Oct/2019 10:59:35] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00Û\x01\x00\x00×\x03\x03÷')
ocr_1      | 172.21.0.3 - - [17/Oct/2019 10:59:35] "Û×÷?ÆÊÙ­ÏØ¶IÊÌóñÔi#åyÔA"~\À,À0À+À/Ì©Ì¨£¢ÌªÀ¯À­À$À(À" HTTPStatus.BAD_REQUEST -

ocr打码工具的日志如上   有谁知道是什么原因吗

**Comment by LeiyuanBlog** [comment]
ocr_1      | Using TensorFlow backend.
ocr_1      | 2019-10-17 10:59:22,567 INFO: 正在下载模型文件...
ocr_1      | 2019-10-17 10:59:23,967 INFO: 下载成功
ocr_1      |
ocr_1      |  * Serving Flask app "web" (lazy loading)
ocr_1      |  * Environment: production
ocr_1      |    WARNING: This is a development server. Do not use it in a production deployment.
ocr_1      |    Use a production WSGI server instead.
ocr_1      |  * Debug mode: off
ocr_1      |  * Running on http://0.0.0.0:8082/ (Press CTRL+C to quit)

启动日志如上

**Comment by pjialin** [comment]
看日志是正常的，可以对接到 py12306 看能否使用
