### ISSUE TITLE
检查完成 开始提交订单  未找到下单账号，3 秒后继续查询

### ISSUE THREAD

**Issue by Samspson** [pjialin/py12306#234]
[ 查询到座位可用 出发时间 20191201 车次 G818 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
未找到下单账号，3 秒后继续查询
[ 查询到座位可用 出发时间 20191201 车次 G822 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
未找到下单账号，3 秒后继续查询

**Comment by Samspson** [comment]
done

**Comment by pjialin** [comment]
看下这个呢，Duplicate of #216
