### ISSUE TITLE
查询余票请求失败	状态码 302   	错误原因 Moved Temporarily  

### ISSUE THREAD

**Issue by tkly** [pjialin/py12306#240]
用户状态已过期，正在重新登录
正在登录用户 tkly
正在下载验证码...
验证码验证成功 开始登录...
# 欢迎回来，tkly #
用户 tkly 心跳正常，下次检测 120 秒后
============================================================
|=== 查询记录恢复成功 上次查询 2019-12-16 16:27:31.937323 ===|
============================================================

查询余票请求失败	状态码 302   	错误原因 Moved Temporarily

**Comment by pjialin** [comment]
Duplicate of #235
