### ISSUE TITLE
购买成功后，发送通知报错 cls.get_station_by(key, 'key').get('name')

### ISSUE THREAD

**Issue by li-coding** [pjialin/py12306#249]
`def get_station_name_by_key(cls, key):
  return cls.get_station_by(key, 'key').get('name')`

报错信息：AttributeError: 'NoneType' object has no attribute 'get'

**Comment by pjialin** [comment]
暂时还没看出什么问题，先关联下 #258

**Comment by li-coding** [comment]
> 暂时还没看出什么问题，先关联下 #258

找到问题了，是因为新开通的站点信息在stations.txt里面找不到。
