### ISSUE TITLE
Windows10 DOS窗口

### ISSUE THREAD

**Issue by dcvincent88** [pjialin/py12306#25]
问一个特别小白的问题

Windows10环境 DOS窗口

运行cp env.py.example env.py
提示“cp不是内部或外部命令，也不是可运行的程序或批处理文件”

以我的浅显了解，'cp'应该是在Linux环境下 用于复制的命令

请问：在windows DOS 界面下，该如何执行“cp env.py.example env.py”语句呢：

**Comment by pjialin** [comment]
在 Windows 下，右键复制 env.py.example，再重命名为 env.py 就可以了
