### ISSUE TITLE
查询余票请求失败	状态码 302   	错误原因 Moved Temporarily   

### ISSUE THREAD

**Issue by amColinzzz** [pjialin/py12306#251]
今天开始,就一直是这个状态:查询余票请求失败	状态码 302   	错误原因 Moved Temporarily   

还有经常验证码下载失败,返回为空.这是不是代表IP被封了,拉取不到验证码?

**Comment by zhangyu68** [comment]
请问最后怎么解决的?

**Comment by DerZc** [comment]
请问这个问题解决了吗
