### ISSUE TITLE
验证码下载失败 错误原因: 返回数据为空 

### ISSUE THREAD

**Issue by amColinzzz** [pjialin/py12306#252]
类似于下面的验证码下载失败,返回数据为空,是指的获取验证码失败吗?如果是这样,会不会因为IP被限制导致获取验证码失败?
有没有什么 小黑屋或者暂歇功能!

`正在登录用户 xiaoli
正在下载验证码...
>> 第 4822 次查询 深圳 -> 郑州 2019-12-20 08:51:11		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.10		停留 1.87		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.06		停留 1.86		

验证码验证成功 开始登录...
登录失败 错误原因: 网络错误
>> 第 4823 次查询 深圳 -> 郑州 2019-12-20 08:51:15		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.19		停留 1.08		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.11		停留 1.59		

>> 第 4824 次查询 深圳 -> 郑州 2019-12-20 08:51:18		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.28		停留 1.24		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.09		停留 0.52		

正在登录用户 xiaoli
正在下载验证码...
验证码下载失败 错误原因: 返回数据为空 5 秒后重试
>> 第 4825 次查询 深圳 -> 郑州 2019-12-20 08:51:20		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.18		停留 1.55		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.16		停留 1.43		

正在下载验证码...
验证码下载失败 错误原因: 返回数据为空 5 秒后重试
>> 第 4826 次查询 深圳 -> 郑州 2019-12-20 08:51:23		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.20		停留 1.79		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.10		停留 1.44		

正在下载验证码...
>> 第 4827 次查询 深圳 -> 郑州 2019-12-20 08:51:27		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.27		停留 1.88		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.17		停留 1.59		

验证码下载失败 错误原因: 返回数据为空 5 秒后重试
>> 第 4828 次查询 深圳 -> 郑州 2019-12-20 08:51:31		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.26		停留 0.91		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.35		停留 1.12		

正在下载验证码...
验证码下载失败 错误原因: 返回数据为空 5 秒后重试
>> 第 4829 次查询 深圳 -> 郑州 2019-12-20 08:51:33		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.21		停留 1.31		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818		G532		G822		G306		*耗时 0.10		停留 1.66		
`

**Comment by pjialin** [comment]
Duplicate of #254
