### ISSUE TITLE
提交订单失败,网络错误.

### ISSUE THREAD

**Issue by amColinzzz** [pjialin/py12306#253]
请问下面这种错误是什么原因?会造成死循环吗?

[ 查询到座位可用 出发时间 20200118 车次 G74 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
提交订单失败，错误原因 网络错误

**Comment by zhouzhuhao** [comment]
今年效果咋样？

**Comment by pjialin** [comment]
一般是被识别到了异常请求，等待程序重试即可
