### ISSUE TITLE
抢到票， 但是总是抢到无座， 我并没有选择无座

### ISSUE THREAD

**Issue by stephen-a2z** [pjialin/py12306#255]

**Comment by pjialin** [comment]
程序是有检测无座不下单的，可否提供下 座位配置，及输出日志

**Comment by stephen-a2z** [comment]
座位设置
``` 'seats': [  # 筛选座位  有先后顺序 :Array
            # 可用值: 特等座, 商务座, 一等座, 二等座, 软卧, 硬卧, 动卧, 软座, 硬座, 无座
            '硬座',
            '二等座',
            '硬卧'
        ]```
日志
```
用户状态已过期，正在重新登录
正在登录用户 330661191@qq.com
正在下载验证码...
验证码验证成功 开始登录...
[ 查询到座位可用 出发时间 20200118 车次 D952 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
查询任务 上海 -> 重庆 正在验证乘客信息
账号正在登录中，3 秒后自动重试
# 欢迎回来，廖宇 #

查询任务 上海 -> 重庆 正在验证乘客信息
# 乘客验证成功 廖宇(成人) #

# 乘客验证成功 廖宇(成人) #

提交订单成功
用户 廖宇 心跳正常，下次检测 120 秒后
检查订单成功
获取排队信息成功，目前排队人数 0, 余票还剩余 199 张
# 提交订单成功！#
第 1 次排队，请耐心等待
第 2 次排队，请耐心等待
第 3 次排队，请耐心等待
第 4 次排队，请耐心等待
第 5 次排队，请耐心等待
第 6 次排队，请耐心等待
第 7 次排队，请耐心等待
第 8 次排队，请耐心等待
第 9 次排队，请耐心等待
第 10 次排队，请耐心等待
第 11 次排队，请耐心等待
第 12 次排队，请耐心等待
第 13 次排队，请耐心等待
第 14 次排队，请耐心等待
第 15 次排队，请耐心等待
第 16 次排队，请耐心等待
第 17 次排队，请耐心等待
第 18 次排队，请耐心等待
第 19 次排队，请耐心等待
第 20 次排队，请耐心等待
第 21 次排队，请耐心等待
第 22 次排队，请耐心等待
排队失败，错误原因 没有足够的票! 
[ 查询到座位可用 出发时间 20200118 车次 D956 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
提交订单成功
检查订单成功
获取排队信息成功，目前排队人数 0, 余票还剩余 982 张
# 提交订单成功！#
第 1 次排队，请耐心等待
第 2 次排队，请耐心等待
第 3 次排队，请耐心等待
第 4 次排队，请耐心等待
第 5 次排队，请耐心等待
第 6 次排队，请耐心等待
第 7 次排队，请耐心等待
第 8 次排队，请耐心等待
第 9 次排队，请耐心等待
第 10 次排队，请耐心等待
第 11 次排队，请耐心等待
第 12 次排队，请耐心等待
第 13 次排队，请耐心等待
第 14 次排队，请耐心等待
第 15 次排队，请耐心等待
用户 廖宇 心跳正常，下次检测 120 秒后
第 16 次排队，请耐心等待
第 17 次排队，请耐心等待
# 车票购买成功，订单号 E268131421 #
语音消息发送失败，请检查 appcode 是否填写正确或 套餐余额是否充足
正在发送语音通知...
当前任务已结束
查询任务 上海 -> 重庆 已结束
```

**Comment by pjialin** [comment]
我这测试没有遇到过这样的情况，还有遇到的朋友可以再打开 issues。
