### ISSUE TITLE
若快已经倒闭

### ISSUE THREAD

**Issue by 17600439700** [pjialin/py12306#259]
希望把若快更新成联众

**Comment by MKe090** [comment]
联众 也不好用 太慢了
还是自己搭建 打码。
根据pjialin 的相关代码可搭建 打码本地服务

py12306/py12306/helpers/api.py 修改如下代码为自己服务网址即可

API_GET_BROWSER_DEVICE_ID = 'https://12306-rail-id-v2.pjialin.com/'
API_FREE_CODE_QCR_API = 'https://12306-ocr.pjialin.com/check/'

**Comment by pjialin** [comment]
Readme 已更新新的打码共享平台
