### ISSUE TITLE
出现warning，是否影响订票？如何debug warning？

### ISSUE THREAD

**Issue by guangmingboy** [pjialin/py12306#26]
WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.

**Comment by pjialin** [comment]
不影响，那个是 flask 的提示，不要将开发机使用到生成环境中，如果介意，可以在运行前设置下环境变量，`export FLASK_ENV=development`，之后再运行

**Comment by guangmingboy** [comment]
谢谢
