### ISSUE TITLE
能成功识码 不能登录问题请教

### ISSUE THREAD

**Issue by MKe090** [pjialin/py12306#261]
使用py12306 使用port:8008、 12306-ocr port:8082、12306-rail-id-v2 port:8081 
搭建后 能成功识码 可是不能登录
请教 问题 谢谢！
![20191221_134757](https://user-images.githubusercontent.com/23100852/71304325-0aeb1580-2400-11ea-8ff8-a7e6b597c063.jpg)

**Comment by pjialin** [comment]
贴上不能登录的日志再打开下，先关了。
