### ISSUE TITLE
登录不了，总是报验证码下载失败

### ISSUE THREAD

**Issue by chengguanghua** [pjialin/py12306#262]
正在下载验证码...
验证码下载失败 错误原因: 返回数据为空 5 秒后重试

**Comment by jiangyongxing** [comment]
我也是这个问题，本地跑了12306-ocr，然后更改api.py 里面的配置为API_FREE_CODE_QCR_API = 'http://127.0.0.1:8082/check/'    都没有用

**Comment by zuijiasunyoubugudan** [comment]
同样遇到这个问题，请求高人指点

**Comment by lon91ong** [comment]
mark  我也是, 改env.py 里面的free为ruokuai后, 可以启用ruokuai的端口
但是free无法启用本地端口, 似乎在哪里写死了, 但是helpers\OCR.py里面逻辑找不出毛病

**Comment by SujinZhao-lib** [comment]
也是这个问题，验证码下载失败，返回数据为空

**Comment by MaoRongH** [comment]
我也是这个问题

**Comment by pjialin** [comment]
已修复 #297
