### ISSUE TITLE
运行成功但是web界面登录422

### ISSUE THREAD

**Issue by jiwenjie** [pjialin/py12306#268]
运行成功了，打开本机地址加8008端口。但是输入用户名和密码一直提示用户名密码错误。我还特意用手机12306登陆了一下。没问题，哪位大佬知道原因啊

**Comment by Allen-Liang** [comment]
web管理员的账号不是自己配置的嘛？跟12306的账号不一样

**Comment by eJayYoung** [comment]
> 运行成功了，打开本机地址加8008端口。但是输入用户名和密码一直提示用户名密码错误。我还特意用手机12306登陆了一下。没问题，哪位大佬知道原因啊

see https://github.com/pjialin/py12306/blob/master/env.docker.py.example#L104
用户名：admin
密码：password
