### ISSUE TITLE
如何保证docker运行的是最新的代码

### ISSUE THREAD

**Issue by DerZc** [pjialin/py12306#273]
您好，我是用docker运行的，请问如何保证docker运行的是最新的代码啊。
我这边每次开始跑都可以登录上去，但是过两分钟就检测到没有登录，然后重新登录的时候就会下载验证码失败，如果手动stop了docker然后重新run之后马上就可以登录成功，请问如何解决。
万分感谢！

**Comment by pjialin** [comment]
参见 #327
