### ISSUE TITLE
请求失败，状态码302，错误原因 Moved Temporarily 

### ISSUE THREAD

**Issue by hyuga0410** [pjialin/py12306#295]
https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-01-23&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=CNQ&purpose_codes=ADULT
<Response [302]>
查询余票请求失败	状态码 302

**Comment by mlch911** [comment]
+1

**Comment by hyuga0410** [comment]
心急吃不了热豆腐，对比了下url，是我的问题，选错了日期，习惯性打成了2019

**Comment by mlch911** [comment]
> 心急吃不了热豆腐，对比了下url，是我的问题，选错了日期，习惯性打成了2019

哈哈我也是，但改了之后还是经常302，Moved Temporarily

**Comment by lanbin45** [comment]
+1 是url写错了吗

**Comment by QAQCoder** [comment]
我也是，2019没改过来，hia~hia~

**Comment by chenmin1992** [comment]
不是吧   是多了两个device的cookie

**Comment by chenmin1992** [comment]
日期填错了  应该是2020年了

**Comment by controlly** [comment]
哈哈，果真，日期写错了

**Comment by pjialin** [comment]
Duplicate of #266
