### ISSUE TITLE
验证码下载失败，返回数据为空，有解决方案吗

### ISSUE THREAD

**Issue by anjina** [pjialin/py12306#297]

**Comment by githubercom** [comment]
搭建本地ocr

**Comment by zdmission** [comment]
![image](https://user-images.githubusercontent.com/28522048/71441305-ecf11e00-273b-11ea-9a2b-bb57f49b30c9.png)
@githubercom 
这样搭建本地OCR，但还是会大概率的出现如下问题：

正在下载验证码...
验证码下载失败 错误原因: 返回数据为空 5 秒后重试

**Comment by anjina** [comment]
> ![image](https://user-images.githubusercontent.com/28522048/71441305-ecf11e00-273b-11ea-9a2b-bb57f49b30c9.png)
> @githubercom
> 这样搭建本地OCR，但还是会大概率的出现如下问题：
> 
> 正在下载验证码...
> 验证码下载失败 错误原因: 返回数据为空 5 秒后重试

所以有更好的方法吗

**Comment by anjina** [comment]
> 搭建本地ocr

大佬能详细讲下吗

**Comment by jiangfubang** [comment]
重试的时候把session中的cookies信息清空一下就行了

**Comment by tongzige** [comment]
是的，把cookies清理一下就好，亲测有效

**Comment by tongzige** [comment]
是的，清理一下cookies就好，亲测有效

**Comment by anjina** [comment]
> 是的，清理一下cookies就好，亲测有效

怎么清理呢，不太懂
