### ISSUE TITLE
登录失败 错误原因: 网络错误,

### ISSUE THREAD

**Issue by amColinzzz** [pjialin/py12306#299]
下面的报错,验证码获取成功,识别成功,但是登陆失败,然后持续下载验证码就会获取失败

正在登录用户 17303******
正在下载验证码...
>> 第 7957 次查询 深圳 -> 郑州 2019-12-25 22:04:04		
出发日期 2020-01-17: 深圳 - 郑州		G72		G280		G80		G74		G818G532		G822		G306		*耗时 0.27		停留 1.98		
出发日期 2020-01-18: 深圳 - 郑州		G72		G280		G80		G74		G818G532		G822		G306		*耗时 0.19		停留 1.62		

验证码验证成功 开始登录...
登录失败 错误原因: 网络错误

**Comment by githubercom** [comment]
是不是12306封的

**Comment by ppu-zengxin** [comment]
老乡，都是往郑州去的
