### ISSUE TITLE
[建议] 在 README 提示使用时留意规避 12306 可能的反刷票策略

### ISSUE THREAD

**Issue by tanchangde** [pjialin/py12306#3]
> 中国铁道科技研究院电子所副总工程师兼12306技术部主任单杏花表示，12306启用风险防控系统，对访问请求实施安全风险识别和分级控制，维护公平公正的售票环境。如果有人以频繁极高的速度访问服务器，会被视为非正常操作，高危用户将被拦截甚至被列入黑名单。还未达到拦截或封号级别的抢票软件将被风控系统拖到慢队列中，也就是说，通过第三方软件抢票可能会更慢。

## 参考资料

- [我用了50个加速包，也没抢到一张火车票](https://mp.weixin.qq.com/s/zuz_qW34WJnET1-oNyZK8Q)
- [“付费加速包”能抢到火车票？“技术黄牛”涉嫌违法违规](http://www.chinanews.com/sh/2019/01-09/8724346.shtml)

**Comment by pjialin** [comment]
嗯，感谢提醒，已加上
