### ISSUE TITLE
为什么没有票的时候会一直报302呢

### ISSUE THREAD

**Issue by fenglijunnb** [pjialin/py12306#304]
查询余票请求失败        状态码 302      错误原因 Moved Temporarily

一直是这个，作者麻烦问一下子

  'left_dates': [  # 出发日期 :Array
            "2019-01-21",
            "2019-01-22",
        ],

时间设置的对着呢

**Comment by tcalan** [comment]
你这个时间错了,应该是2020年吧，19年1月份早就过了

**Comment by fenglijunnb** [comment]
确实不太好意思啊，这个眼睛和脑子对不上，还好你提醒了一下，不然回家的票永远都抢不到了 @tcalan

**Comment by pjialin** [comment]
Duplicate of #266
