### ISSUE TITLE
uamtk票据内容为空

### ISSUE THREAD

**Issue by oubingbing** [pjialin/py12306#314]
您好，我想咨询一下，{"result_message":"uamtk票据内容为空","result_code":2}是什么原因导致的

https://kyfw.12306.cn/passport/web/auth/uamtk

这一步我是请求了，但是

https://exservice.12306.cn/excater/uamauthclient

却返回 {"result_message":"uamtk票据内容为空","result_code":2}

希望您回复一下，谢谢

**Comment by ShengZhang2016** [comment]
请问你有log的截图吗？登陆是否成功？

**Comment by oubingbing** [comment]
以及解决了，谢谢
