### ISSUE TITLE
为啥登录失败，提示用户名错误

### ISSUE THREAD

**Issue by fusj001** [pjialin/py12306#315]

**Comment by qcr10nrh** [comment]
我也是这个问题呀，不知道为什么

**Comment by cjwfly1988** [comment]
我没问题的啊。

**Comment by 1451297455** [comment]
我的也是这样    没法玩

**Comment by cjwfly1988** [comment]
你们在哪里找的用户名跟密码？

**Comment by qcr10nrh** [comment]
自己12306的用户名和密码呀？不对吗？罗强-------- 原始邮件 --------发件人： cjwfly1988 <notifications@github.com>日期： 2019年12月31日周二 20:51收件人： pjialin/py12306 <py12306@noreply.github.com>抄送： qcr10nrh <qcr10nrh@163.com>, Comment <comment@noreply.github.com>主    题： Re: [pjialin/py12306] 为啥登录失败，提示用户名错误 (#315)你们在哪里找的用户名跟密码？

**Comment by cjwfly1988** [comment]
web UI界面管理不是用12306的用户民跟密码，看看evn 文件。

**Comment by cjwfly1988** [comment]
@qcr10nrh  你是尝试登陆localhost:8008 那个WEB UI管理界面是吗？

**Comment by qcr10nrh** [comment]
> @qcr10nrh 你是尝试登陆localhost:8008 那个WEB UI管理界面是吗？

我在env.py中找到了账号密码。WEB UI界面的密码在env.py里边，不是12306账号。

**Comment by cjwfly1988** [comment]
对的，那这个问题可以关闭了

**Comment by qcr10nrh** [comment]
是的，我没有问题了
