### ISSUE TITLE
提交订单提示验证乘客信息时总显示账号正在初始化

### ISSUE THREAD

**Issue by Monus7** [pjialin/py12306#32]
<img width="889" alt="screen shot 2019-01-15 at 1 15 53 pm" src="https://user-images.githubusercontent.com/35139509/51160182-cdb10600-18c7-11e9-9962-7ad892194132.png">

**Comment by Monus7** [comment]
多谢 辛苦您啦

**Comment by Jandaes** [comment]
请问下、我是刚clone下来的、也是一直出现这个、这是怎么回事？

**Comment by Monus7** [comment]
> 请问下、我是刚clone下来的、也是一直出现这个、这是怎么回事？
把第一项设置中 account_key 设置成 你要买票的那个人名

**Comment by Monus7** [comment]
把 user_accounts 中的 key 设置成 你要买票的那个人名
