### ISSUE TITLE
服务器用docker部署，api.py文件路劲在哪里？

### ISSUE THREAD

**Issue by Hsiaopan** [pjialin/py12306#324]
想用服务器自己的打码 `api` ，但是找不到这个 `api.py` 文件

**Comment by ShengZhang2016** [comment]
你是说这个吗？
https://github.com/pjialin/py12306/blob/master/py12306/helpers/api.py

**Comment by Hsiaopan** [comment]
> 你是说这个吗？
> https://github.com/pjialin/py12306/blob/master/py12306/helpers/api.py

是这个，但是docker部署之后找不到这个文件了

**Comment by ShengZhang2016** [comment]
我还没试docker，不好意思啊，希望来个大佬看看

**Comment by pjialin** [comment]
将这个文件映射到 docker 中即可
```
-v api.py:/code/py12306/helpers/api.py
```
