### ISSUE TITLE
docker如何更新项目代码

### ISSUE THREAD

**Issue by xiangfeigao** [pjialin/py12306#327]
刚接触docker，确实好东西，现在我想与项目代码同步，如何更新呢？每次重新生成镜像，这个自然之道，有更加好的方式吗，请指教

**Comment by xiangfeigao** [comment]
是不是用docker pull命令

**Comment by ADACharlotter** [comment]
直接把整个目录映射出来,然后从github上面下载覆盖就行了吧

**Comment by pjialin** [comment]
docker 镜像是自动更新的， 重新 `docker pull` 镜像即可
