### ISSUE TITLE
使用 docker-compose 构建报错

### ISSUE THREAD

**Issue by doublewinter0** [pjialin/py12306#331]
![image](https://user-images.githubusercontent.com/22414051/71615537-a80e3100-2bec-11ea-9e7a-aa7dcd92b9eb.png)
看起来是安装依赖出问题了, 大佬们看下!

**Comment by zepc007** [comment]
同报错

**Comment by pjialin** [comment]
看报错是网络问题，重试或检查下吧。

**Comment by quking** [comment]
我的用docker-compose 构建报错 TypeError: a bytes-like object is required, not 'str'

**Comment by doublewinter0** [comment]
我把 docker 默认的网桥恢复后就好了!
也是就把 daemon.json 里面的 bridge 字段去掉, 重启 docker!
