### ISSUE TITLE
Mac os使用docker的方式运行会两秒后自动退出

### ISSUE THREAD

**Issue by iqiqiya** [pjialin/py12306#343]
问题描述：
按照README中的docker方式进行操作，会出现容器自动退出的情况，两秒之内可以打开127.0.0.1:8008，然后就不行了
如下图所示：
![sc_20200103184927](https://user-images.githubusercontent.com/43666095/71719727-30453e00-2e5a-11ea-9b50-d3685ae7c420.png)

**Comment by pjialin** [comment]
看下上面日志呢，修改下对应配置即可
