### ISSUE TITLE
然后修改 py12306/helpers/api.py ,docker方式跑的py12306，请教下怎么修改api.py

### ISSUE THREAD

**Issue by lyslys888** [pjialin/py12306#344]

**Comment by David2k13** [comment]
同问

**Comment by tardistao** [comment]
QQ群文档（780289875），[网络错误问题临时解决方案](http://zht.fwy.plus/%E7%BD%91%E7%BB%9C%E9%94%99%E8%AF%AF%E9%97%AE%E9%A2%98%E4%B8%B4%E6%97%B6%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.pdf)

**Comment by pjialin** [comment]
Duplicate of #324
