### ISSUE TITLE
提交成功之后不能自动结束

### ISSUE THREAD

**Issue by playstarLee** [pjialin/py12306#35]
我提交成功之后怎么又在排队？无法自动退出吗？

=== 正在进行第 291 次查询 邯郸 -> 漯河 === 2019-01-15 14:02:21.862580
[ 查询到座位可用 出发时间 20190208 车次 G521 座位类型 二等座 余票数量 2 ]
检查完成 开始提交订单 
提交订单成功
检查订单成功
排队成功，你当前排在第 0 位, 余票还剩余 246 张
 提交订单成功
排队等待中，排队人数 111，预计还需要 4 秒
第 1 次排队，请耐心等待
排队等待中，排队人数 118，预计还需要 4 秒
第 2 次排队，请耐心等待
排队等待中，排队人数 189，预计还需要 6 秒
第 3 次排队，请耐心等待
排队等待中，排队人数 129，预计还需要 4 秒

而且排队的人数不是越来越少，而是有时候多有时候少？

**Comment by pjialin** [comment]
排队人数的 12306 服务器返回的。排队有超时的，超时会自动退出

**Comment by pjialin** [comment]
#40
