### ISSUE TITLE
更新之后build docker 失败

### ISSUE THREAD

**Issue by dllen** [pjialin/py12306#358]
Could not find a version that satisfies the requirement pyppeteer-box==0.0.27 (from -r requirements.txt (line 20)) (from versions: 0.0.26)
No matching distribution found for pyppeteer-box==0.0.27 (from -r requirements.txt (line 20))

**Comment by pjialin** [comment]
阿里云的源包还没同步过去，换成清华的了，已经可以了

**Comment by dllen** [comment]
好像还是不行 @pjialin

**Comment by pjialin** [comment]
提供错误日志 @dllen

**Comment by dllen** [comment]
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting pyppeteer-box==0.0.27 (from -r requirements.txt (line 20))
  Could not find a version that satisfies the requirement pyppeteer-box==0.0.27 (from -r requirements.txt (line 20)) (from versions: 0.0.26)
No matching distribution found for pyppeteer-box==0.0.27 (from -r requirements.txt (line 20))
You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

@pjialin  谢谢

**Comment by pjialin** [comment]
@dllen 试试 
```
pip install --upgrade pyppeteer-box 
```
还不行的话可以提供下操作系统版本，python 版本

**Comment by dllen** [comment]
> @dllen 试试
> 
> ```
> pip install --upgrade pyppeteer-box 
> ```
> 
> 还不行的话可以提供下操作系统版本，python 版本
多谢 回复
我 进入项目目录 运行 docker build . -t py12306 出现这个错误的

**Comment by pjialin** [comment]
@dllen 试了下，这个文件在国外的服务器上是可以下载的，估计还是同步比较慢的问题。
```
https://pypi.tuna.tsinghua.edu.cn/packages/2f/2f/1c3cb44d3eb7d73527dc2e04dff06f876184ca2622109676906dc9a7d47d/pyppeteer-box-0.0.27.tar.gz
```
可以尝试删除 `requirements.txt` 的第一行再 `build` 或者使用 `docker hub` 上的镜像，已经是最新的
