### ISSUE TITLE
每次心跳检查都会重新打码？120秒的心跳检测我的若快打码账号顶不住啊，不能做成检查登陆状态吗，只有失效的时候再重新登陆

### ISSUE THREAD

**Issue by yangxvhao** [pjialin/py12306#37]

**Comment by pjialin** [comment]
心跳检测就是为了确保登录状态的，正常一次登录是可以维护 1 天左右的，频繁重新登录说明 ip 被限制了或则 账号在其它地方登录

**Comment by yangxvhao** [comment]
> 心跳检测就是为了确保登录状态的，正常一次登录是可以维护 1 天左右的，频繁重新登录说明 ip 被限制了或则 账号在其它地方登录

ok,了解了
