### ISSUE TITLE
配置疑问

### ISSUE THREAD

**Issue by tzkang** [pjialin/py12306#38]
你好，按照使用手册，需要配置的文件就是`env.py`，相关的用户信息，即购买者信息、购买车次均是在该问题下填写对吧？ 但是我填写的12306账号的密码是明显错误的，运行程序依然显示在刷票，不会报告任何错误，这个如何处理？

**Comment by pjialin** [comment]
查询和用户是分离的，用户密码错误在登录的时候会进行提示的，不影响查询

**Comment by tzkang** [comment]
@pjialin 所以，我如何判断我的用户已经正常登陆，然后刷票遇到有余票可以自动提交订单呢？

**Comment by pjialin** [comment]
网页或日志中都可以看到的

**Comment by tzkang** [comment]
@pjialin 好的，说到网页，这里有一个问题，就是我参照使用步骤部署（略过Docker部分）好，但是本地web页面还是无法显示出来（httpd已经正确配置，并启动）。

**Comment by pjialin** [comment]
程序自带 web 服务器，开启后访问你的 host + 端口就可以

**Comment by tzkang** [comment]
就是将这个字段`WEB_ENABLE = 1  # 是否打开 Web 管理`默认配置为1就行对吧？  但是还是无法展示web页面

**Comment by pjialin** [comment]
具体信息描述下吧，怎么操作的，反馈是什么

**Comment by tzkang** [comment]
部署使用的就是手册中**使用**版块的**1、2、3、4**步，第4步为运行程序，配置文件`env.py`只是修改了`USER_ACCOUNTS`以及`QUERY_JOBS`字段相关信息，其他均是默认的，然后运行程序可以查询，但是本地浏览器输入127.0.0.1:8008显示为  无法访问此页面

**Comment by fanpengustc** [comment]
程序运行在远程服务器上 ，怎么设置本地web查看

**Comment by pjialin** [comment]
确保服务器端口已打开，访问服务器 ip:端口

**Comment by tzkang** [comment]
启动页面如下
![image](https://user-images.githubusercontent.com/22320884/51253286-d6ddc800-19d8-11e9-804e-62d70869cdda.png)

web字段设置如下：
![image](https://user-images.githubusercontent.com/22320884/51253384-10163800-19d9-11e9-96b1-0a1fe062c4b7.png)

但就是无法登录

**Comment by tzkang** [comment]
就在刚刚把http服务协助，重装之后，就可以顺利登录了。  
谢谢啦。

**Comment by tzkang** [comment]
问题2：程序跑了五分钟，即出现如下报错：
![image](https://user-images.githubusercontent.com/22320884/51256881-64bdb100-19e1-11e9-87b0-8f79bfe42bc6.png)
如何解决？

**Comment by pjialin** [comment]
目前还看不到。

错误截图看不到具体错误信息，可以往下截点

**Comment by tzkang** [comment]
好的，这会儿不运行了，我退出了运行界面，之前的报错信息就看不到了。如果明天再出现类似情况的时候，再截图反馈给你。

**Comment by pjialin** [comment]
程序会自动重试的

**Comment by tzkang** [comment]
另外就是，最近IP封禁严重，如果遭到IP封禁，程序运行过程中会有报错之类的提示吗？ 或者web页面有相关状态的反应？

**Comment by venhow** [comment]
admin的密码是什么？

**Comment by pjialin** [comment]
@tzkang 经常网络失败就是 ip 被限制了

@venhow  env.py
```python
# Web 管理
WEB_ENABLE = 1  # 是否打开 Web 管理
WEB_USER = {  # 登录信息
    'username': 'admin',
    'password': 'password'
}
WEB_PORT = 8008  # 监听端口
```

**Comment by tzkang** [comment]
@pjialin 好的，谢谢及时回复。 还有就是之前提到的一个问题，就是我从web前端页面去看，是无法确认我的购买者是谁，只能显示账户信息和状态，是吗？

**Comment by pjialin** [comment]
是的
