### ISSUE TITLE
关于通知的问题

### ISSUE THREAD

**Issue by playstarLee** [pjialin/py12306#40]
我发现我排队抢票后很多次抢到票了，可没有显示抢票成功的提示，而是继续登录，抢票，然后出现这样的提示：
提交订单失败，错误原因 ['您还有未处理的订单，请您到<a href="../view/train_order.html">[未完成订单]</a>进行处理!'] 
这就造成我本来已经抢到票，却没有消息推送，希望作者能够改进一下！

**Comment by Forevertruth** [comment]
为什么我的显示一直在排队中，几次都会显示错误，然后又重新排队，错误原因-4
