### ISSUE TITLE
有大佬可以打包成exe文件吗

### ISSUE THREAD

**Issue by xiaoxin0** [pjialin/py12306#45]
小白实在是看不懂，安装完依赖，不懂怎么修改配置，可以出一个视频教程吗？
有注释的地方可以理解，其他地方不太懂，直接运行测试，提示错误

**Comment by xiaoxin0** [comment]
来自一个想回家的小白，恳请帮助

**Comment by zsg0601** [comment]
主要po主没有把步骤写的很详细，所以大部分不玩linux的同学并不是很明白。
如果是在Linux下修改配置，你要了解vi 编辑方法，或者你fork本项目，然后自己修改配置代码上传github，直接clone自己的项目运行就可以。

**Comment by pjialin** [comment]
@xiaoxin0 
运行测试，测试完成程序会自动结束的，要访问 web 页面需要在非测试模式下打开

配置中 0 代表关闭，1 代表开启

email 中 `SERVER_USER` 是登录的用户名 `SERVER_PASSWORD` 是登录的密码

**Comment by Hamishcn** [comment]
写了个用commandlines上input配置的 要不要提pr？

**Comment by xiaoxin0** [comment]
可以发给我一份吗？谢谢🙏

Hamish <notifications@github.com>于2019年1月18日 周五下午2:04写道：

**Comment by Hamishcn** [comment]
@xiaoxin0 等owner回覆看提不提pr上來吧。

**Comment by Hamishcn** [comment]
[https://github.com/pjialin/py12306/pull/81#issue-245886568](url)

**Comment by Hamishcn** [comment]
[PR](https://github.com/pjialin/py12306/pull/81#issue-245886568)

**Comment by pjialin** [comment]
后面会在 Web 页面增加配置修改的功能，做成 exe 暂时没有计划
