### ISSUE TITLE
建议加入定时抢票，23点-6点自动暂停

### ISSUE THREAD

**Issue by staoran** [pjialin/py12306#46]
目前好像还没有定时抢票，23点-6点自动暂停这两个功能吧？
另外建议加一个更便宜的语音服务商？
https://market.aliyun.com/products/56928004/cmapi026600.html?spm=5176.2020520132.101.3.49e772181bOmQX#sku=yuncode2060000000
1元／25次
4.9元／100次??????
48元／1000次??????
比如这家，很迷人的定价策略。。。。

**Comment by pjialin** [comment]
定时抢票目前还没实现，暂时可以通过缩短间隔实现

23点-6点 会自动暂停的

另外这个服务商之前测试过，模板内容没法达到想要的效果就放弃了

**Comment by staoran** [comment]
后期的查询任务有可能支持改签么

**Comment by pjialin** [comment]
后面可以在 web 里实现
