### ISSUE TITLE
各位大佬      这个项目，现在还能用吗   时间:2023/12/7

### ISSUE THREAD

**Issue by Liam011205** [pjialin/py12306#463]
各位大佬      这个项目，现在还能用吗   时间:2023/12/7

**Comment by handsomeBoy2233** [comment]
能，我才试了

**Comment by xu-huadong** [comment]
可以 
![fccf12addc13a82b32b16711dd0cbb3d](https://github.com/pjialin/py12306/assets/24771599/86026e6b-6790-4744-be5a-7a4910218d61)

**Comment by qwq2023qwq** [comment]
> 可以 ![fccf12addc13a82b32b16711dd0cbb3d](https://private-user-images.githubusercontent.com/24771599/295238382-86026e6b-6790-4744-be5a-7a4910218d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODY2MjAsIm5iZiI6MTcwNDg4NjMyMCwicGF0aCI6Ii8yNDc3MTU5OS8yOTUyMzgzODItODYwMjZlNmItNjc5MC00NzQ0LWJlNWEtN2E0OTEwMjE4ZDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDExMzIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YmVmZDZlZWE0YzU3ZWUwNjAyZjk4MjU5MTE4M2MxNTRlYjRlMTE2MTk3NjE5YmNhMmYyMDI0ZjIzMDQ2ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WeukQs7QjA7bNuIWJA9WPw9FAl6mNC-lyBO4687B5g8)

我这边一直在查询不下单怎么办
![image](https://github.com/pjialin/py12306/assets/90580525/91dea339-829d-4cba-9222-d032ed71b81c)

**Comment by handsomeBoy2233** [comment]
配置文件没有修改好，它都没有查询到车号，你把列车号注释掉，让它默认选择全部

**Comment by qwq2023qwq** [comment]
> 配置文件没有修改好，它都没有查询到车号，你把列车号注释掉，让它默认选择全部

找到问题了，筛选车次里的引号没删

**Comment by zhnghijin** [comment]
> > 配置文件没有修改好，它都没有查询到车号，你把列车号注释掉，让它默认选择全部
> 
> 找到问题了，筛选车次里的引号没删

allow_train_numbers = ['K824']不是这里删引号吧

**Comment by qwq2023qwq** [comment]
> > > 配置文件没有修改好，它都没有查询到车号，你把列车号注释掉，让它默认选择全部
> > 
> > 
> > 找到问题了，筛选车次里的引号没删
> 
> allow_train_numbers = ['K824']不是这里删引号吧

'K824'整个部分都需要删除到

**Comment by GDbbq** [comment]
我没成功登陆

**Comment by lovesnsfi** [comment]
我正准备试一下的呢？

**Comment by RicardoWYP** [comment]
总是滑动验证码识别失败是怎么回事啊

**Comment by qwq2023qwq** [comment]
> 总是滑动验证码识别失败是怎么回事啊



> 我没成功登陆

12306改验证方式了，改成了输入密码后还要短信验证码，配置文件里登录方式改回qr就行了

**Comment by yuanyue** [comment]
![image](https://github.com/pjialin/py12306/assets/7209635/b536190e-4ea8-400e-8acf-f98110e5fb92)

请问我一直不下单怎么办，我用站票测试的

**Comment by Liam011205** [comment]
> ![image](https://private-user-images.githubusercontent.com/7209635/298317216-b536190e-4ea8-400e-8acf-f98110e5fb92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzkwNTEsIm5iZiI6MTcwNTk3ODc1MSwicGF0aCI6Ii83MjA5NjM1LzI5ODMxNzIxNi1iNTM2MTkwZS00ZWE4LTQwMGUtOGFjZi1mOTgxMTBlNWZiOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDI1OTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZiYmFmYjAxZjk0MzA3ZGEyYzhmZjBmMDJkNDliN2Q1ZTU0MjE5NTU5YTlkNTAzOTgzYjk1OTRiMjI1YjRjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-ztLamY4auVA2gq0cyzJ9neYdLHxKdsmJHXQSC5VfX8)
> 
> 请问我一直不下单怎么办，我用站票测试的

不知道，我没用站票，一下就成功啦
![image](https://github.com/pjialin/py12306/assets/130265701/2761b8c9-1554-40d9-9cd8-572d5bd6f732)

**Comment by Liam011205** [comment]
![image](https://github.com/pjialin/py12306/assets/130265701/7ce7febc-48e9-4030-8584-138e0b1f53c3)
谁知道我这个是啥错误，我买的yiyuan的语音服务，代码就按上面改的，但结果是下面的失败
![image](https://github.com/pjialin/py12306/assets/130265701/dacb69b0-c317-4e1f-8c9d-a5ccce205b53)

**Comment by kongzhongfeima** [comment]
> ![image](https://private-user-images.githubusercontent.com/130265701/298793251-7ce7febc-48e9-4030-8584-138e0b1f53c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODAxMzEsIm5iZiI6MTcwNTk3OTgzMSwicGF0aCI6Ii8xMzAyNjU3MDEvMjk4NzkzMjUxLTdjZTdmZWJjLTQ4ZTktNDAzMC04NTg0LTEzOGUwYjFmNTNjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMzE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjcxNDdmNjFmZWRlMmI5MzMxNWEyMTQwZGM1M2U4YWM4NmQ0ZDRiMGU3N2VjMGJmZTMwNTNiZjY4ZWQzNmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GzbH3uZSMD6iYuBmZNSgChfA_yvIGZxCSPbqBACMOHA) 谁知道我这个是啥错误，我买的yiyuan的语音服务，代码就按上面改的，但结果是下面的失败 ![image](https://private-user-images.githubusercontent.com/130265701/298793626-dacb69b0-c317-4e1f-8c9d-a5ccce205b53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODAxMzEsIm5iZiI6MTcwNTk3OTgzMSwicGF0aCI6Ii8xMzAyNjU3MDEvMjk4NzkzNjI2LWRhY2I2OWIwLWMzMTctNGUxZi04YzlkLWE1Y2NjZTIwNWI1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMzE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmE0MDkxMzBjNmQ5MmIxYjhiMjE1M2RlZGY1MjA0N2IwYjhlZDIzNWUyNWZiNDE1OTRiYmU1MmQzZGI1NWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.22ACCBqjBniibDSnnVrF0mK1291XDFUbjBsBMF-FfAw)

这个不是显示购票成功了吗，哪个语音通知有啥用啊

**Comment by Liam011205** [comment]
> > ![image](https://private-user-images.githubusercontent.com/130265701/298793251-7ce7febc-48e9-4030-8584-138e0b1f53c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODAxMzEsIm5iZiI6MTcwNTk3OTgzMSwicGF0aCI6Ii8xMzAyNjU3MDEvMjk4NzkzMjUxLTdjZTdmZWJjLTQ4ZTktNDAzMC04NTg0LTEzOGUwYjFmNTNjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMzE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjcxNDdmNjFmZWRlMmI5MzMxNWEyMTQwZGM1M2U4YWM4NmQ0ZDRiMGU3N2VjMGJmZTMwNTNiZjY4ZWQzNmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GzbH3uZSMD6iYuBmZNSgChfA_yvIGZxCSPbqBACMOHA) 谁知道我这个是啥错误，我买的yiyuan的语音服务，代码就按上面改的，但结果是下面的失败 ![image](https://private-user-images.githubusercontent.com/130265701/298793626-dacb69b0-c317-4e1f-8c9d-a5ccce205b53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODAxMzEsIm5iZiI6MTcwNTk3OTgzMSwicGF0aCI6Ii8xMzAyNjU3MDEvMjk4NzkzNjI2LWRhY2I2OWIwLWMzMTctNGUxZi04YzlkLWE1Y2NjZTIwNWI1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMzE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmE0MDkxMzBjNmQ5MmIxYjhiMjE1M2RlZGY1MjA0N2IwYjhlZDIzNWUyNWZiNDE1OTRiYmU1MmQzZGI1NWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.22ACCBqjBniibDSnnVrF0mK1291XDFUbjBsBMF-FfAw)
> 
> 这个不是显示购票成功了吗，哪个语音通知有啥用啊

难道不用给我们发短信提醒吗，我们不可能一直坐在电脑旁边看pycharm吧，就是有订单成功后，给我们提醒

**Comment by EvViolet** [comment]
> > 配置文件没有修改好，它都没有查询到车号，你把列车号注释掉，让它默认选择全部
> 
> 找到问题了，筛选车次里的引号没删

大哥，你是指env.py里面的配置吗

**Comment by GDbbq** [comment]
这个有分流抢票好用吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月25日 18:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [pjialin/py12306] 各位大佬      这个项目，现在还能用吗   时间:2023/12/7 (Issue #463) |

配置文件没有修改好，它都没有查询到车号，你把列车号注释掉，让它默认选择全部

找到问题了，筛选车次里的引号没删

大哥，你是指env.py里面的配置吗
