### ISSUE TITLE
Docker 启动后，一直提示查询地址获取失败, 正在重新获取 

### ISSUE THREAD

**Issue by lovelinessmoe** [pjialin/py12306#476]
![image](https://github.com/pjialin/py12306/assets/32808610/57cbfba2-a894-4382-8963-138f6db38c42)

**Comment by lovelinessmoe** [comment]
web管理端也进不去

**Comment by Liam011205** [comment]
> web管理端也进不去

api.py里的配置改了吗，499议题里面有

**Comment by lovelinessmoe** [comment]
> > web管理端也进不去
> 
> api.py里的配置改了吗，499议题里面有

谢谢兄弟，现在好了

**Comment by guoyuenan1** [comment]
> > web管理端也进不去
> 
> api.py里的配置改了吗，499议题里面有

请问下499议题是啥？
