### ISSUE TITLE
# 车票购买成功，订单号 test # 这正常嘛？

### ISSUE THREAD

**Issue by xingxinggo** [pjialin/py12306#486]
[ 查询到座位可用 出发时间 20240208 车次 D7128 座位类型 无座 余票数量 1 ]
余票数小于乘车人数，当前余票数: 1, 实际人数 2, 删减人车人数到: 1
检查完成 开始提交订单
# 删减后的乘客列表 陈xx(成人) #
# 车票购买成功，订单号 test #
发送成功，请检查微信
当前任务已结束
查询任务 广州东 -> 潮汕 已结束

非测试模式

**Comment by xingxinggo** [comment]
刷了2天才发现预设 IS_DEBUG =true

**Comment by zjinpeng** [comment]
我这老是要刷码验证，几分钟得扫一次，你们呢

**Comment by HuobiOfficial** [comment]
> 我这老是要刷码验证，几分钟得扫一次，你们呢

同，一模一样

**Comment by wuxianyu9908** [comment]
请问你们是用的什么打码工具

**Comment by xingxinggo** [comment]
纯纯手工活，人机（电脑）机（手机）合一，除了不停扫码，还要不停登入app
