### ISSUE TITLE
可以微信通知

### ISSUE THREAD

**Issue by qingzew** [pjialin/py12306#5]
https://github.com/littlecodersh/ItChat

itchat，使用python调用微信

**Comment by pjialin** [comment]
ok，放到计划列表中

**Comment by pjialin** [comment]
嗯，容器没设置时区，我修改下

关于打码，请看最近更新 @qingzew

**Comment by demostars** [comment]
建议曲线救国：Server酱 微信推送即可

**Comment by HeiSir2014** [comment]
微信通知 还是用Server酱 ，开发快，集成比较方便。一个KEY搞定配置，一个HTTP搞定推送。

**Comment by xuej2s** [comment]
也可以考虑用钉钉群里的自定义机器人，一个http请求就可以

**Comment by pjialin** [comment]
嗯，钉钉和TG 都有大佬实现了，后面还是做个 POST 吧，方便一些 
#22
