### ISSUE TITLE
为什么会出现排队，不理解

### ISSUE THREAD

**Issue by jazefe** [pjialin/py12306#50]
```
提交订单成功
检查订单成功
排队成功，你当前排在第 0 位, 余票还剩余 325 张
# 提交订单成功！#
排队等待中，排队人数 41，预计还需要 4 秒
第 1 次排队，请耐心等待
排队等待中，排队人数 35，预计还需要 4 秒
第 2 次排队，请耐心等待
排队等待中，排队人数 1，预计还需要 4 秒
第 3 次排队，请耐心等待
排队等待中，排队人数 104，预计还需要 4 秒
第 4 次排队，请耐心等待
排队等待中，排队人数 120，预计还需要 4 秒
第 5 次排队，请耐心等待
排队等待中，排队人数 19，预计还需要 4 秒
第 6 次排队，请耐心等待
排队等待中，排队人数 34，预计还需要 4 秒
第 7 次排队，请耐心等待
排队等待中，排队人数 10，预计还需要 4 秒
第 8 次排队，请耐心等待
排队等待中，排队人数 37，预计还需要 4 秒
第 9 次排队，请耐心等待
排队等待中，排队人数 26，预计还需要 4 秒
第 10 次排队，请耐心等待
排队等待中，排队人数 99，预计还需要 4 秒
第 11 次排队，请耐心等待
排队等待中，排队人数 19，预计还需要 4 秒

第 12 次排队，请耐心等待
排队等待中，排队人数 1，预计还需要 4 秒
第 13 次排队，请耐心等待
排队等待中，排队人数 1，预计还需要 4 秒
第 14 次排队，请耐心等待
排队等待中，排队人数 0，预计还需要 4 秒
第 15 次排队，请耐心等待
排队等待中，排队人数 49，预计还需要 4 秒
第 16 次排队，请耐心等待
排队等待中，排队人数 50，预计还需要 4 秒
第 17 次排队，请耐心等待
排队等待中，排队人数 55，预计还需要 4 秒
第 18 次排队，请耐心等待
排队等待中，排队人数 1，预计还需要 4 秒
第 19 次排队，请耐心等待
排队等待中，排队人数 79，预计还需要 4 秒
第 20 次排队，请耐心等待
# 车票购买成功，订单号 E445593482 #
发送成功，请检查微信
当前任务已结束
```

使用客户端买票需要排队吗？好像没见过排队的现象啊，那咱们这儿排队是为什么呢？排队人数也不规则变化

**Comment by pjialin** [comment]
是需要排队的， 排队人数是 12306 返回的。

**Comment by sandove** [comment]
> ```
> 提交订单成功
> 检查订单成功
> 排队成功，你当前排在第 0 位, 余票还剩余 325 张
> # 提交订单成功！#
> 排队等待中，排队人数 41，预计还需要 4 秒
> 第 1 次排队，请耐心等待
> 排队等待中，排队人数 35，预计还需要 4 秒
> 第 2 次排队，请耐心等待
> 排队等待中，排队人数 1，预计还需要 4 秒
> 第 3 次排队，请耐心等待
> 排队等待中，排队人数 104，预计还需要 4 秒
> 第 4 次排队，请耐心等待
> 排队等待中，排队人数 120，预计还需要 4 秒
> 第 5 次排队，请耐心等待
> 排队等待中，排队人数 19，预计还需要 4 秒
> 第 6 次排队，请耐心等待
> 排队等待中，排队人数 34，预计还需要 4 秒
> 第 7 次排队，请耐心等待
> 排队等待中，排队人数 10，预计还需要 4 秒
> 第 8 次排队，请耐心等待
> 排队等待中，排队人数 37，预计还需要 4 秒
> 第 9 次排队，请耐心等待
> 排队等待中，排队人数 26，预计还需要 4 秒
> 第 10 次排队，请耐心等待
> 排队等待中，排队人数 99，预计还需要 4 秒
> 第 11 次排队，请耐心等待
> 排队等待中，排队人数 19，预计还需要 4 秒
> 
> 第 12 次排队，请耐心等待
> 排队等待中，排队人数 1，预计还需要 4 秒
> 第 13 次排队，请耐心等待
> 排队等待中，排队人数 1，预计还需要 4 秒
> 第 14 次排队，请耐心等待
> 排队等待中，排队人数 0，预计还需要 4 秒
> 第 15 次排队，请耐心等待
> 排队等待中，排队人数 49，预计还需要 4 秒
> 第 16 次排队，请耐心等待
> 排队等待中，排队人数 50，预计还需要 4 秒
> 第 17 次排队，请耐心等待
> 排队等待中，排队人数 55，预计还需要 4 秒
> 第 18 次排队，请耐心等待
> 排队等待中，排队人数 1，预计还需要 4 秒
> 第 19 次排队，请耐心等待
> 排队等待中，排队人数 79，预计还需要 4 秒
> 第 20 次排队，请耐心等待
> # 车票购买成功，订单号 E445593482 #
> 发送成功，请检查微信
> 当前任务已结束
> ```
> 使用客户端买票需要排队吗？好像没见过排队的现象啊，那咱们这儿排队是为什么呢？排队人数也不规则变化

老铁你可以自己试试，官方客户端也是要排队的
