### ISSUE TITLE
关于提醒问题，无法通知完成了哪个任务，希望作者改进，谢谢

### ISSUE THREAD

**Issue by xiaoxin0** [pjialin/py12306#51]
作者你好，我用的邮件提醒，多任务那种，当我成功后，无法看到是哪个任务完成，有可能会导致付不上款。

所以建议作者 邮件提醒时加上：任务某某完成，提高下辨识度，谢谢作者
还有问题就是：请问各位大佬，有没有其他提醒方式可以满足我的需求，即：提醒模板具有辨识度，可以分辨哪个任务或者账号完成的

万分感谢

**Comment by Nuh123** [comment]
麻烦问一下那个邮箱设置的登录名和登录密码是设置的发送邮箱的嘛

**Comment by pjialin** [comment]
是的 @Nuh123

**Comment by Nuh123** [comment]
> 是的 @Nuh123

邮件发送失败，请手动检查配置，错误原因 [WinError 10061] 由于目标计算机积极拒绝，
无法连接。

那这个问题是python的问题还是QQ邮箱的问题，我发送邮箱设置的QQ邮箱？？
