### ISSUE TITLE
验证码下载失败  状态码500

### ISSUE THREAD

**Issue by U-23** [pjialin/py12306#53]
ip被封了么，翻墙也一样

验证码下载失败 错误原因: 返回数据为空 5 秒后重试
正在下载验证码...

还没有成功登录上去过。。。。。

**Comment by staoran** [comment]
大概率IP被封了，重启光猫或者路由器吧，不行就多重启几次，感觉他们是按IP段来封的······你可以直接去https://kyfw.12306.cn/otn/resources/login.html试一下，可以直观看出自己有没有被封

**Comment by pcshao** [comment]
kill by ip. suggest you net with mobile network.

**Comment by U-23** [comment]
> 大概率IP被封了，重启光猫或者路由器吧，不行就多重启几次，感觉他们是按IP段来封的······你可以直接去[https://kyfw.12306.cn/otn/resources/login.html试一下，可以直观看出自己有没有被封](https://kyfw.12306.cn/otn/resources/login.html%E8%AF%95%E4%B8%80%E4%B8%8B%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%9B%B4%E8%A7%82%E7%9C%8B%E5%87%BA%E8%87%AA%E5%B7%B1%E6%9C%89%E6%B2%A1%E6%9C%89%E8%A2%AB%E5%B0%81)

测试了多次，已解决
