### ISSUE TITLE
运行测试时报错，请大佬帮忙看看

### ISSUE THREAD

**Issue by achaorg** [pjialin/py12306#56]
[root@asrv5 py12306]# python main.py -t -n
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/home/chris/py12306/py12306/app.py", line 8, in <module>
    from py12306.helpers.func import *
  File "/home/chris/py12306/py12306/helpers/func.py", line 155
    def dict_count_key_num(data: dict, key, like=False):
                               ^
SyntaxError: invalid syntax

**Comment by pjialin** [comment]
检查下 python 版本是否在 3.6 及以上

**Comment by achaorg** [comment]
[root@asrv5 py12306]# python3
Python 3.6.8 (default, Jan 16 2019, 11:02:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.

必须的

**Comment by achaorg** [comment]
> 检查下 python 版本是否在 3.6 及以上

[root@asrv5 py12306]# python3
Python 3.6.8 (default, Jan 16 2019, 11:02:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.


必须的，大佬

**Comment by pjialin** [comment]
运行时也应该使用 python3 运行
```
python3 main.py -t -n
```
