### ISSUE TITLE
只查询在有余票的情况下也要有提醒

### ISSUE THREAD

**Issue by kbj** [pjialin/py12306#6]
看了下目前的逻辑是只有下单成功后才会发送提醒要求支付，可是当没有设置12306账号也就是只查询余票的情况下，检查到有余票的时候如果没提醒的话不看日志人根本不知道的吧。 

建议没添加账号的时候查询到有余票时也应该要有提醒。（另外，能同时支持下`POST`请求通知最好，方便推送微信或者TG）

感谢作者的分享!

**Comment by pjialin** [comment]
嗯，会加上查询时余票提醒，微信通知已经放到 todo 中了，post 请求可以放到以后，暂时没计划
