### ISSUE TITLE
[求助]联系人选择

### ISSUE THREAD

**Issue by Vixb1122** [pjialin/py12306#68]
第一个问题：
有同名同姓的两个常用联系人，怎么选择特定的人？
第二个问题：
同一个人，使用不同证件添加到联系人，怎么选择特定证件？

**Comment by pjialin** [comment]
抱歉啊，好像两个问题目前都是无法实现的，可以删减联系人或者使用多个账号解决

**Comment by Vixb1122** [comment]
> 抱歉啊，好像两个问题目前都是无法实现的，可以删减联系人或者使用多个账号解决

后续会解决这个问题么，通过证件号匹配人

**Comment by pjialin** [comment]
已增加序号选择唯一联系人功能
