### ISSUE TITLE
关于具体环境的疑问

### ISSUE THREAD

**Issue by Nuh123** [pjialin/py12306#69]
![default](https://user-images.githubusercontent.com/42088349/51312750-f6332e80-1a86-11e9-800f-4820b0d10de6.png)
python没玩过，不知道搞得合适不？添加了一个票很多的行程都不自己下单。感觉是我哪没搞合适。希望懂的人指教一下。

**Comment by Nuh123** [comment]
> 把你配置共享出来，记得把账号密码、名字、key、token这些打码，

![default](https://user-images.githubusercontent.com/42088349/51389889-b5134b00-1b68-11e9-8446-d436e07f7eff.png)
![default](https://user-images.githubusercontent.com/42088349/51389892-b6dd0e80-1b68-11e9-814f-c7b12a70e6aa.png)
这两个是我在web界面截到的，其中广州到东莞那趟是测试用的。然后就发现一个问题，那个筛选车次的数组里填上内容的话，即使是有相应余票的情况下也不会下单。但是一旦把那个数组设为空数组就可以买上。所以我认为其它设置应该没有问题。  不知道问题出在哪。

**Comment by Nuh123** [comment]
![default](https://user-images.githubusercontent.com/42088349/51390152-716d1100-1b69-11e9-96bd-c1b34447209e.png)
这个是我任务配置界面的情况，确定这几个车次中有有票的车，结合上面的，查询任务界面也能看到车次筛选应该是成功的，但是再对比其它任务，在日志界面有发现设置了筛选车次的任务，反倒不显示任务对应的车次情况。

**Comment by Nuh123** [comment]
![1](https://user-images.githubusercontent.com/42088349/51390352-04a64680-1b6a-11e9-91fc-28d21785314b.png)
![2](https://user-images.githubusercontent.com/42088349/51390355-0708a080-1b6a-11e9-8693-d43e6cfa830f.png)
![3](https://user-images.githubusercontent.com/42088349/51390358-0839cd80-1b6a-11e9-9b3d-70e11c2c6a68.png)
这个是我测试时的命令行输出情况，但是一运行就是最开始显示的那种情况，但是web管理界面是正常的。测试时我也能收到我设置的相应渠道的通知，就是想不通我那个数组哪写的有问题。

**Comment by Nuh123** [comment]
我装的3.7的python，安装时选了添加环境变量和pip。环境变量的path里面找不到python，但是可以在任意盘符下python进入python界面。我通过git下载后，直接pip安装不了依赖，网上看到说用python -m pip，试了然后就安装好了。配置参数那个语句在git里输入了一下之后文件夹里就出现了一个env.py的文件，我就修改了它，然后在文件夹界面的命令行输入了相应的测试和运行语句（没有在git是因为git里乱码）。以上就是我的操作步骤，还望懂得人指导一下，看有没有弄错的地方，第一次玩python，很紧张（手动狗头、狗头）

**Comment by Nuh123** [comment]
分布式那边，因为不太会搞，所以还没仔细研究就卡在不下单这步上了。我尝试了语言、微信通知，也都成功了，邮箱设置那，我用qq给网易邮箱发，下面也输入了正确的qq邮箱密码和账号，那个localhost那里我没有动，测试时就说什么10006，就是发送不了。若快也设置成功了。

**Comment by alalbb313** [comment]
查询和下单功能分离 , 查看你配置文件中的12306账户所定义的KEY 是否为 下单使用账号的KEY .
USER_ACCOUNTS 中的 key 与 QUERY_JOBS 中的 account_key 一致 .

**Comment by Hamishcn** [comment]
qq郵箱不是只用賬號密碼的，還要個授權碼。

**Comment by Nuh123** [comment]
> 查询和下单功能分离 , 查看你配置文件中的12306账户所定义的KEY 是否为 下单使用账号的KEY .
> USER_ACCOUNTS 中的 key 与 QUERY_JOBS 中的 account_key 一致 .

这个我看过 了，账号设置里的key和任务中的key是一致，虽然添加了多任务，但账号只有一个。而且，我只要把那个筛选车次的数次删空之后就能买到，数组有内容就买不到，感觉应该是在数组的书写格式那里有问题，但是仔细检查了几遍没有看出那里有问题呀！！而且我之前不小心在多乘客的那个数组不小心书写格式有点问题，命令行界面就会提醒语法有问题，但车次那个没有报错。

**Comment by Nuh123** [comment]
> qq郵箱不是只用賬號密碼的，還要個授權碼。

谢谢，因为其它通知方式以及能通知到， 所以就没有细究邮箱的通知方式。不过还是很好奇，那个授权码是填在邮箱服务的那个host那里吗？？

**Comment by Hamishcn** [comment]
@Nuh123 qq郵箱的授權碼就是密碼的 host是smtp.qq.com

**Comment by Nuh123** [comment]
> @Nuh123 qq郵箱的授權碼就是密碼的 host是smtp.qq.com

那关于穷前面说到的筛选车次数组有效性的问题，请问你知道吗？

**Comment by Hamishcn** [comment]
@Nuh123 git pull origin master之後看看還復現嗎

**Comment by Nuh123** [comment]
> @Nuh123 git pull origin master之後看看還復現嗎

嗯嗯，我重新拉了更新之后的版本，试过，没有问题，谢谢你的帮助。
