### ISSUE TITLE
提交订单失败 错误原因 - 

### ISSUE THREAD

**Issue by godhangyu** [pjialin/py12306#72]
rt

**Comment by godhangyu** [comment]
=== 正在进行第 226112 次查询 xt -> bj === 2019-01-18 06:10:10.206358
[ 查询到座位可用 出发时间 20190210 车次 G72 座位类型 二等座 余票数量 9 ]
检查完成 开始提交订单
提交订单失败，错误原因 -

**Comment by Starbucksstar** [comment]
[ 查询到座位可用 出发时间 20190211 车次 G858 座位类型 二等座 余票数量 2 ]
检查完成 开始提交订单 
提交订单成功
检查订单成功
获取排队信息成功，目前排队人数 0, 余票还剩余 558 张
出票失败，错误原因 余票不足！

**为啥每次有余票了，提交订单成功，排队也成功，最后都是出票失败！？**

**Comment by pjialin** [comment]
返回余票不足说明只是缓存数据，程序会自动重试的
