### ISSUE TITLE
the program stop in this statu 

### ISSUE THREAD

**Issue by zhb0920** [pjialin/py12306#74]
####### py12306 购票助手，本程序为开源工具，请勿用于商业用途 ########

日志已输出到文件中: runtime/12306.log

WEB 管理页面已开启，请访问 主机地址 + 端口 8008 进行查看

 * Serving Flask app "py12306.web.web" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

**Comment by pjialin** [comment]
#26
