### ISSUE TITLE
排完队以后抢到票了但是未通知，会继续抢票

### ISSUE THREAD

**Issue by Gahon1995** [pjialin/py12306#75]
继续抢票的时候会提示有未支付订单，希望能够加个检测，有未支付订单的时候也发一个通知，然后停止抢票

**Comment by U-23** [comment]
同问 ，用的ServerChan通知，可以发送测试消息。抢到票 ，下完订单却没有发送通知，且后台会继续抢票。

**Comment by pjialin** [comment]
最近提交已修复，先关了
