### ISSUE TITLE
经常弹出这个。。。

### ISSUE THREAD

**Issue by adaaaaaa** [pjialin/py12306#80]
查询余票请求失败	状态码 500
有时候2，3次查询弹一次，有时候是每次都有。。。

**Comment by Hamishcn** [comment]
考慮ip位址段封鎖

**Comment by alalbb313** [comment]
查询超时, 线程close.  检查网络环境.

**Comment by adaaaaaa** [comment]
@alalbb313 @Hamishcn 
今天我又试了一下，不开CDN真的一点报错都没有。。。而且查询快。。。
开了之后，就是报错加翻倍的耗时。。。

**Comment by adaaaaaa** [comment]
难道是我的网络不适合开CDN？不太懂。。。

**Comment by pjialin** [comment]
#79

**Comment by adaaaaaa** [comment]
@alalbb313 @Hamishcn 你们用CDN和不用的差距有多大？？

**Comment by alalbb313** [comment]
> @alalbb313 @Hamishcn 你们用CDN和不用的差距有多大？？

不开启CDN 默认使用本地查询, 开启CDN使用CDN远程查询(先这样理解) , 按照你这样说本地查询正常, CDN查询有问题 , 简单测试 "开始菜单"->"运行"->"cmd"->"ping 117.27.245.54"
找个CDN ping 测试一下是否延长很高, 或者是杀毒软件防火墙的问题.
我本地装了 cfosspeed 出现过你这个问题, 卸载之后正常.

**Comment by adaaaaaa** [comment]
@alalbb313 
`[captain@captain-pc ~]$ ping 117.27.245.54
PING 117.27.245.54 (117.27.245.54) 56(84) bytes of data.
64 bytes from 117.27.245.54: icmp_seq=4 ttl=47 time=45.7 ms
64 bytes from 117.27.245.54: icmp_seq=5 ttl=48 time=53.8 ms
64 bytes from 117.27.245.54: icmp_seq=16 ttl=48 time=50.2 ms
64 bytes from 117.27.245.54: icmp_seq=32 ttl=49 time=50.6 ms
64 bytes from 117.27.245.54: icmp_seq=33 ttl=48 time=47.3 ms
^C
--- 117.27.245.54 ping statistics ---
33 packets transmitted, 5 received, 84.8485% packet loss, time 392ms
rtt min/avg/max/mdev = 45.705/49.514/53.794/2.814 ms
`
卧槽。。。这是什么状况。。。ping www.qq.com都不会掉包。。。

**Comment by Hamishcn** [comment]
我不用cdn的。。

**Comment by adaaaaaa** [comment]
换了一个网络，还是一样，CDN比不用CDN要慢很多。。。
