### ISSUE TITLE
python3 运行时  Segmentation fault 

### ISSUE THREAD

**Issue by liicos** [pjialin/py12306#82]
python3 main.py 时 直接报Segmentation fault , 该怎么办 ~

**Comment by pjialin** [comment]
贴下具体报错信息

**Comment by liicos** [comment]
![image](https://user-images.githubusercontent.com/29332099/51422498-63130980-1bea-11e9-8f90-99634252ffa9.png)
没有报错信息额, runtime/

**Comment by Hamishcn** [comment]
試下ulimit -a 看 core size是否為0 不為0 運行程后gdb core-file core 貼圖。

**Comment by liicos** [comment]
> 试下ulimit -a核心大小是否为0不为0运行程后gdb核心文件核心贴图。

![image](https://user-images.githubusercontent.com/29332099/51423069-965a9600-1bf4-11e9-9161-678619fedca5.png)

**Comment by liicos** [comment]
![image](https://user-images.githubusercontent.com/29332099/51423350-e425cd00-1bf9-11e9-9260-aed99a34aad0.png)

**Comment by liicos** [comment]
> 試下ulimit -a 看 core size是否為0 不為0 運行程后gdb core-file core 貼圖。

图在上面 , 我的python版本是3.7.0 按照 https://blog.csdn.net/elija940818/article/details/79238813 这个网址的教程安装的

**Comment by liicos** [comment]
换了3.6.5的Python版本 , 解决了
