### ISSUE TITLE
国人的悲哀，原则上讲为了和别人竞争的抢票属于技术作恶

### ISSUE THREAD

**Issue by a358003542** [pjialin/py12306#84]
国人的悲哀，原则上讲为了和别人竞争的抢票属于技术作恶

**Comment by liuw5367** [comment]
美团，飞猪，去哪儿，携程，智行 等等各种软件抢票算什么呢？ 你说这话 有什么意思

**Comment by pjialin** [comment]
如果觉得有问题可以去其它论坛中讨论，自然有人解答，issue 不是讨论这个的地方
