### ISSUE TITLE
docker启动失败的情况。

### ISSUE THREAD

**Issue by c2ch** [pjialin/py12306#86]
用docker启动一直没有反应，后来自己改了下。可以启动了（如果你们的启动失败，可以尝试下这种情况，不一定对你们有效）。
步骤如下：
1、最好保证当前目录是干净的，什么都没有。
2、下载配置文件，
docker run --rm pjialin/py12306 cat /config/env.py > env.py 或者
curl https://raw.githubusercontent.com/pjialin/py12306/master/env.docker.py.example -o env.py
3、修改你的配置
4、启动
docker run --rm --name py12306 -p 8008:8008 -d -v $(pwd):/config  pjialin/py12306（就这行命令变了）

**Comment by pjialin** [comment]
启动失败可以通过 `docker logs 容器 ID` 查看具体原因

一般出错都是 env.py 配置的问题，通过报错信息检查下就好了
