### ISSUE TITLE
web端帮助文档始终打不开。。。

### ISSUE THREAD

**Issue by adaaaaaa** [pjialin/py12306#89]
另外，web端可不可以增加一个更新按钮？

**Comment by alalbb313** [comment]
![image](https://user-images.githubusercontent.com/7855714/51425380-455b9980-1c16-11e9-8cf5-24bd9d2d3702.png)
web 帮助文档使用的是github 上的本项目的readme.md , 还是检查你的网络问题!!!!

**Comment by adaaaaaa** [comment]
@alalbb313 
我的网络怎么检查？感觉不到问题。。。另外，web 帮助文档使用的确实不是github 上的。。。
鼠标放上面，链接显示是：http://192.168.21.104:8008/#/help/readme

**Comment by adaaaaaa** [comment]
奇怪，又打开了，之前无论等多久都打不开。。。没有动过任何网络设置。。。
