### ISSUE TITLE
nohup python3 main.py #执行后台任务 这个命令未生效

### ISSUE THREAD

**Issue by lwb9428000** [pjialin/py12306#92]
最后一步 nohup python3 main.py #执行后台任务 这个命令未生效，断开 xshell 链接后 web 页面就不能访问，抢票任务也停止了。请问各位大神，怎么解决。

输入 nohup python3 main.py
提示：nohup: ignoring input and appending output to ‘nohup.out’

输入 python3 main.py
提示：日志已输出到文件中: runtime/12306.log

WEB 管理页面已开启，请访问 主机地址 + 端口 8008 进行查看

 * Serving Flask app "py12306.web.web" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

**Comment by alalbb313** [comment]
`nohup python3 main.py &`
