### ISSUE TITLE
建议增加能够指定姓名相同、但证件不同的乘车人

### ISSUE THREAD

**Issue by yanxin9210** [pjialin/py12306#94]
- 12306联系人中支持录入姓名相同、证件不同的联系人，如分别通过身份证、护照添加联系人“张三”，在12306bypass 上会分别显示为“张三[成人]”、"张三[护照]"
- 如果 py12306 已经支持了该功能，请教下该如何设置呢？如果没有，希望能增加该功能

**Comment by Vixb1122** [comment]
#68 ，问题重复，解决方式为：[env.py.example#L130](https://github.com/pjialin/py12306/blob/master/env.py.example#L130)

**Comment by yanxin9210** [comment]
> #68 ，问题重复，解决方式为：[env.py.example#L130](https://github.com/pjialin/py12306/blob/master/env.py.example#L130)

好的，已经设置好了，谢谢
