### ISSUE TITLE
出票失败，错误原因 余票不足！

### ISSUE THREAD

**Issue by zkl99999** [pjialin/py12306#95]
[ 查询到座位可用 出发时间 20190201 车次 G1277 座位类型 二等座 余票数量 1 ]
余票数小于乘车人数，当前余票数: 1, 实际人数 2, 删减人车人数到: 1
检查完成 开始提交订单 
 删减后的乘客列表 xxx(成人) #
提交订单成功
检查订单成功
获取排队信息成功，目前排队人数 0, 余票还剩余 415 张
出票失败，错误原因 余票不足！

这是速度不够,我已经开了四个线程了?大家其他参数都怎么配置的

**Comment by zkl99999** [comment]
已经显示提交订单成功了,,为啥 还出票失败呢

**Comment by zkl99999** [comment]
web端显示最后心跳 是 1970年呢

**Comment by adaaaaaa** [comment]
凉了50年了。。。😂

**Comment by pjialin** [comment]
@zkl99999  提交成功之后还要经历很多流程，出票失败很正常的

最后心跳显示在下次检测完心跳之后会更新

**Comment by adaaaaaa** [comment]
> [ 查询到座位可用 出发时间 20190201 车次 G1277 座位类型 二等座 余票数量 1 ]
> 余票数小于乘车人数，当前余票数: 1, 实际人数 2, 删减人车人数到: 1
> 检查完成 开始提交订单
> 删减后的乘客列表 xxx(成人) #
> 提交订单成功
> 检查订单成功
> 获取排队信息成功，目前排队人数 0, 余票还剩余 415 张
> 出票失败，错误原因 余票不足！
> 
> 这是速度不够,我已经开了四个线程了?大家其他参数都怎么配置的
你是怎么开到4线程的？配置文件里只有开关啊。。。

**Comment by pjialin** [comment]
@adaaaaaa 感觉很多人把线程开关写成数字了😂
